// Shared news items for Market News sidebar
const newsItems = [
    {
        id: 'cipher-digital-slips-3-despite-20-year-barber-lake',
        emoji: '📰',
        title: 'Cipher Digital Slips 3% Despite 20-year Barber Lake Lease Extension; TeraWulf Retreats 2%, IREN Limited Treads Water',
        date: 'Wed, September 30, 2026 at 4:17 PM UTC 2 min read',
        timestamp: '2026-09-30T16:17:48+00:00',
        preview: 'TeraWulf (WULF) saw its stock retreat by 2% following the announcement of a 20-year lease extension for Barber Lake, which was perceived as a mixed si...',
        stockSymbol: 'WULF'
    },
    {
        id: 'packaging-innovations-sonoco-s-snack-hack-for-mars',
        emoji: '📰',
        title: 'Packaging innovations: Sonoco’s snack hack for Mars, Amcor flips for pet food',
        date: 'Thu, October 1, 2026 at 3:53 PM UTC 3 min read',
        timestamp: '2026-10-01T15:53:00+00:00',
        preview: 'Sonoco has introduced a new packaging innovation aimed at enhancing snack products for Mars, while Amcor has shifted its focus to developing packaging...',
        stockSymbol: 'AMC.AX'
    },
    {
        id: 'brightspire-capital-inc-announces-third-quarter-20',
        emoji: '📰',
        title: 'BrightSpire Capital, Inc. Announces Third Quarter 2026 Earnings Release and Conference Call Dates',
        date: 'Thu, October 1, 2026 at 8:05 PM UTC 3 min read',
        timestamp: '2026-10-01T20:05:00+00:00',
        preview: 'BrightSpire Capital, Inc. has announced the release date for its third quarter 2026 earnings report, along with a scheduled conference call for invest...',
        stockSymbol: 'BRSP'
    },
    {
        id: 'circle-crcl-stock-looks-fairly-valued-despite-fres',
        emoji: '📰',
        title: 'Circle (CRCL) Stock Looks Fairly Valued Despite Fresh USDC Partnership News',
        date: 'Wed, September 30, 2026 at 4:11 PM UTC 3 min read',
        timestamp: '2026-09-30T16:11:47+00:00',
        preview: 'Circle (CRCL) stock remains fairly valued following the announcement of a new partnership involving USDC, a stablecoin that has gained traction in the...',
        stockSymbol: 'CRCL'
    },
    {
        id: 'should-you-buy-the-dip-in-uipath-stock',
        emoji: '📰',
        title: 'Should You Buy The Dip In UiPath Stock?',
        date: 'Wed, September 30, 2026 at 3:34 PM UTC 3 min read',
        timestamp: '2026-09-30T15:34:55+00:00',
        preview: 'UiPath (PATH) has experienced a notable dip in its stock price, prompting discussions among investors about whether this presents a buying opportunity...',
        stockSymbol: 'PATH'
    },
    {
        id: 'ge-healthcare-gehc-upgraded-to-buy-here-s-why',
        emoji: '📰',
        title: 'GE HealthCare (GEHC) Upgraded to Buy: Here\'s Why',
        date: 'Wed, September 30, 2026 at 3:00 PM UTC 2 min read',
        timestamp: '2026-09-30T15:00:03+00:00',
        preview: 'GE HealthCare (GEHC) has been upgraded to a "Buy" rating by analysts, reflecting a positive outlook on the company\'s growth potential and financial pe...',
        stockSymbol: 'GEHC'
    },
    {
        id: 'cava-group-cava-rises-as-market-takes-a-dip-key-fa',
        emoji: '📰',
        title: 'Cava Group (CAVA) Rises As Market Takes a Dip: Key Facts',
        date: 'Wed, September 30, 2026 at 8:50 PM UTC 3 min read',
        timestamp: '2026-09-30T20:50:03+00:00',
        preview: 'Cava Group (CAVA) saw its stock price increase despite a broader market downturn, indicating strong investor confidence in the company\'s performance. ...',
        stockSymbol: 'CAVA'},
    {id: 'miami-international-holdings-announces-date-of-thi',
        emoji: '📰',
        title: 'Miami International Holdings Announces Date of Third Quarter 2026 Earnings Release and Conference Call',
        date: 'Thu, October 1, 2026 at 10:45 AM UTC 2 min read',
        timestamp: '2026-10-01T10:45:00+00:00',
        preview: 'Miami International Holdings has announced the date for its third quarter 2026 earnings release and accompanying conference call. This event is signif...',
        stockSymbol: 'MIAX'},
    {id: 'can-corning-s-at-t-deal-boost-its-optical-communic',
        emoji: '📰',
        title: 'Can Corning\'s AT&T Deal Boost Its Optical Communications Growth?',
        date: 'Thu, October 1, 2026 at 1:40 PM UTC 4 min read',
        timestamp: '2026-10-01T13:40:00+00:00',
        preview: 'Corning has announced a strategic partnership with AT&T to enhance its optical communications segment, aiming to expand fiber optic infrastructure. Th...',
        stockSymbol: 'T'},
    {id: 'vici-properties-inc-vici-stock-declines-while-mark',
        emoji: '📰',
        title: 'VICI Properties Inc. (VICI) Stock Declines While Market Improves: Some Information for Investors',
        date: 'Thu, October 1, 2026 at 9:15 PM UTC 4 min read',
        timestamp: '2026-10-01T21:15:05+00:00',
        preview: 'VICI Properties Inc. (VICI) experienced a decline in its stock price despite an overall improvement in the market. This drop may raise concerns for in...',
        stockSymbol: 'VICI'},
    {id: 'coherent-lumentum-and-ciena-stocks-surge-on-bullis',
        emoji: '📰',
        title: 'Coherent, Lumentum, and Ciena stocks surge on bullish Wall Street call',
        date: 'Thu, October 1, 2026 at 6:29 PM UTC 3 min read',
        timestamp: '2026-10-01T18:29:06+00:00',
        preview: 'Coherent, Lumentum, and Ciena stocks experienced a significant surge following a bullish call from Wall Street analysts, indicating strong future grow...',
        stockSymbol: 'COHR'},
    {id: '1-small-cap-stock-for-long-term-investors-and-2-we',
        emoji: '📰',
        title: '1 Small-Cap Stock for Long-Term Investors and 2 We Ignore',
        date: 'Thu, October 1, 2026 at 12:13 PM UTC 4 min read',
        timestamp: '2026-10-01T12:13:07+00:00',
        preview: 'In a recent analysis, a small-cap stock was highlighted as a promising long-term investment opportunity, while two others were deemed unworthy of atte...',
        stockSymbol: 'FOR'},
    {id: 'oscar-health-inc-oscr-stock-dips-while-market-gain',
        emoji: '📰',
        title: 'Oscar Health, Inc. (OSCR) Stock Dips While Market Gains: Key Facts',
        date: 'Thu, October 1, 2026 at 9:00 PM UTC 3 min read',
        timestamp: '2026-10-01T21:00:05+00:00',
        preview: 'Oscar Health, Inc. (OSCR) experienced a decline in its stock price despite overall market gains. This drop may raise concerns among investors about th...',
        stockSymbol: 'OSCR'},
    {id: 'sblk-vs-kex-which-stock-should-value-investors-buy',
        emoji: '📰',
        title: 'SBLK vs. KEX: Which Stock Should Value Investors Buy Now?',
        date: 'Thu, October 1, 2026 at 2:40 PM UTC 3 min read',
        timestamp: '2026-10-01T14:40:02+00:00',
        preview: 'In a recent comparison between SBLK and KEX, analysts highlighted KEX as a potentially more attractive option for value investors due to its solid fun...',
        stockSymbol: 'KEX'},
    {id: 'rogers-stock-surges-11-after-investor-day-here-s-w',
        emoji: '📰',
        title: 'Rogers Stock Surges 11% After Investor Day. Here’s Why',
        date: 'Thu, October 1, 2026 at 2:00 AM UTC 4 min read',
        timestamp: '2026-10-01T02:00:18+00:00',
        preview: 'Rogers Communications\' stock surged 11% following its recent Investor Day, where the company outlined its strategic plans and growth initiatives. This...',
        stockSymbol: 'ROG'},
    {id: 'investors-heavily-search-super-group-sghc-limited',
        emoji: '📰',
        title: 'Investors Heavily Search Super Group (SGHC) Limited (SGHC): Here is What You Need to Know',
        date: 'Thu, October 1, 2026 at 12:00 PM UTC 4 min read',
        timestamp: '2026-10-01T12:00:03+00:00',
        preview: 'Super Group (SGHC) Limited has seen a significant increase in investor interest, as searches for the company surged recently. This heightened attentio...',
        stockSymbol: 'SGHC'},
    {id: 'red-cat-s-blue-ops-expands-maritime-defense-operat',
        emoji: '📰',
        title: 'Red Cat’s Blue Ops Expands Maritime Defense Operations Through Strategic Partnership with Florida Atlantic University',
        date: 'Thu, October 1, 2026 at 4:51 PM UTC 2 min read',
        timestamp: '2026-10-01T16:51:00+00:00',
        preview: 'Red Cat Holdings\' subsidiary, Blue Ops, has formed a strategic partnership with Florida Atlantic University to enhance its maritime defense operations...',
        stockSymbol: 'RCAT'},
    {id: 'moderna-mrna-stock-dips-while-market-gains-key-fac',
        emoji: '📰',
        title: 'Moderna (MRNA) Stock Dips While Market Gains: Key Facts',
        date: 'Thu, October 1, 2026 at 8:50 PM UTC 2 min read',
        timestamp: '2026-10-01T20:50:05+00:00',
        preview: 'Moderna (MRNA) stock experienced a decline despite overall market gains, reflecting investor concerns over the company\'s future growth prospects follo...',
        stockSymbol: 'MRNA'},
    {id: 'saic-saic-up-1-1-since-last-earnings-report-can-it',
        emoji: '📰',
        title: 'SAIC (SAIC) Up 1.1% Since Last Earnings Report: Can It Continue?',
        date: 'Wed, September 30, 2026 at 2:30 PM UTC 2 min read',
        timestamp: '2026-09-30T14:30:01+00:00',
        preview: 'SAIC\'s stock has risen 1.1% since its last earnings report, indicating a positive market response to its financial performance. This uptick suggests i...',
        stockSymbol: 'SAIC'},
    {id: 'acm-research-announces-participation-in-18th-annua',
        emoji: '📰',
        title: 'ACM Research Announces Participation in 18th Annual CEO Investor Summit 2026',
        date: 'Wed, September 30, 2026 at 8:05 PM UTC 4 min read',
        timestamp: '2026-09-30T20:05:00+00:00',
        preview: 'ACM Research has announced its participation in the 18th Annual CEO Investor Summit scheduled for 2026. This event provides a platform for the company...',
        stockSymbol: 'ACMR'},
    {id: 'why-eagle-bancorp-montana-inc-ebmt-is-a-top-divide',
        emoji: '📰',
        title: 'Why Eagle Bancorp Montana, Inc. (EBMT) is a Top Dividend Stock for Your Portfolio',
        date: 'Wed, September 30, 2026 at 2:45 PM UTC 2 min read',
        timestamp: '2026-09-30T14:45:04+00:00',
        preview: 'Eagle Bancorp Montana, Inc. (EBMT) has been highlighted as a top dividend stock due to its consistent dividend payments and strong financial performan...',
        stockSymbol: 'EBMT'},
    {id: 'bristol-myers-squibb-s-dividend-sustainability-hin',
        emoji: '📰',
        title: 'Bristol Myers Squibb’s Dividend Sustainability Hinges on One Critical Cash Flow Metric',
        date: 'Wed, September 30, 2026 at 3:45 PM UTC 4 min read',
        timestamp: '2026-09-30T15:45:53+00:00',
        preview: 'Bristol Myers Squibb\'s recent analysis highlights that the sustainability of its dividend is heavily reliant on a key cash flow metric. This is signif...',
        stockSymbol: 'BMY'},
    {id: 'regeneron-sanofi-expand-alliance-in-deal-worth-up',
        emoji: '📰',
        title: 'Regeneron, Sanofi Expand Alliance in Deal Worth Up to $8 Billion',
        date: 'Thu, October 1, 2026 at 3:02 PM UTC 3 min read',
        timestamp: '2026-10-01T15:02:02+00:00',
        preview: 'Sanofi (SAN.PA) has expanded its alliance with Regeneron in a deal potentially worth up to $8 billion. This collaboration aims to enhance the developm...',
        stockSymbol: 'SAN.PA'},
    {id: 'is-stronger-guidance-record-bookings-and-new-debt',
        emoji: '📰',
        title: 'Is Stronger Guidance, Record Bookings and New Debt Refinancing Altering The Investment Case For Norwegian Cruise Line (NCLH)?',
        date: 'Fri, October 2, 2026 at 3:10 AM UTC 3 min read',
        timestamp: '2026-10-02T03:10:37+00:00',
        preview: 'Norwegian Cruise Line Holdings (NCLH) has issued stronger guidance alongside record bookings and a successful debt refinancing. This positive momentum...',
        stockSymbol: 'NCLH'},
    {id: 'bank-ozk-announces-increase-to-quarterly-common-st',
        emoji: '📰',
        title: 'Bank OZK Announces Increase to Quarterly Common Stock Dividend and Announces Preferred Stock Dividend',
        date: 'Thu, October 1, 2026 at 8:01 PM UTC 2 min read',
        timestamp: '2026-10-01T20:01:00+00:00',
        preview: 'Bank OZK has announced an increase in its quarterly common stock dividend, reflecting the bank\'s strong financial performance and commitment to return...',
        stockSymbol: 'OZK'},
    {id: 'evgo-eyes-17-000-stalls-by-2030-as-tesla-deal-expa',
        emoji: '📰',
        title: 'EVgo Eyes 17,000 Stalls by 2030 as Tesla Deal Expands Its EV Charging Reach',
        date: 'Thu, October 1, 2026 at 10:02 AM UTC 4 min read',
        timestamp: '2026-10-01T10:02:06+00:00',
        preview: 'EVgo has announced plans to expand its electric vehicle charging network to 17,000 stalls by 2030, bolstered by a new partnership with Tesla. This exp...',
        stockSymbol: 'EVGO'},
    {id: 'can-higher-fleet-utilization-boost-avis-budget-s-p',
        emoji: '📰',
        title: 'Can Higher Fleet Utilization Boost Avis Budget\'s Profitability?',
        date: 'Thu, October 1, 2026 at 4:53 PM UTC 4 min read',
        timestamp: '2026-10-01T16:53:00+00:00',
        preview: 'Avis Budget Group is exploring strategies to enhance fleet utilization, which could significantly improve profitability. Increased fleet efficiency is...',
        stockSymbol: 'CAR'},
    {id: 'applovin-falls-3-as-wells-fargo-calls-pixel-instal',
        emoji: '📰',
        title: 'AppLovin Falls 3% as Wells Fargo Calls Pixel Install Spike a False Start; Trade Desk Sits Out the Selloff, Magnite Dips',
        date: 'Thu, October 1, 2026 at 4:02 PM UTC 4 min read',
        timestamp: '2026-10-01T16:02:10+00:00',
        preview: 'Magnite (MGNI) experienced a dip following a 3% decline in AppLovin\'s stock, as Wells Fargo labeled a recent spike in Pixel installs as a false start....',
        stockSymbol: 'MGNI'},
    {id: 'inspire-medical-systems-inc-announces-approval-of',
        emoji: '📰',
        title: 'Inspire Medical Systems, Inc. Announces Approval of New Hypoglossal Nerve Stimulation CPT® Codes by the AMA Editorial Panel',
        date: 'Thu, October 1, 2026 at 8:03 PM UTC 2 min read',
        timestamp: '2026-10-01T20:03:00+00:00',
        preview: 'Inspire Medical Systems, Inc. announced the approval of new Current Procedural Terminology (CPT) codes for its hypoglossal nerve stimulation therapy b...',
        stockSymbol: 'INSP'},
    {id: 'what-to-expect-from-ge-aerospace-s-q3-2026-earning',
        emoji: '📰',
        title: 'What to Expect From GE Aerospace\'s Q3 2026 Earnings Report',
        date: 'Wed, September 30, 2026 at 6:30 PM UTC 4 min read',
        timestamp: '2026-09-30T18:30:51+00:00',
        preview: 'GE Aerospace is set to release its Q3 2026 earnings report, with analysts anticipating strong performance driven by increased demand for commercial ai...',
        stockSymbol: 'GE'},
    {id: 'synchrony-financial-syf-could-be-20-below-fair-val',
        emoji: '📰',
        title: 'Synchrony Financial (SYF) Could Be 20% Below Fair Value Following Vetspire Partnership',
        date: 'Wed, September 30, 2026 at 8:11 PM UTC 3 min read',
        timestamp: '2026-09-30T20:11:52+00:00',
        preview: 'Synchrony Financial (SYF) has entered a partnership with Vetspire, a veterinary software company, which analysts suggest could position the stock appr...',
        stockSymbol: 'SYF'},
    {id: 'why-waste-management-wm-dipped-more-than-broader-m',
        emoji: '📰',
        title: 'Why Waste Management (WM) Dipped More Than Broader Market Today',
        date: 'Wed, September 30, 2026 at 9:15 PM UTC 3 min read',
        timestamp: '2026-09-30T21:15:03+00:00',
        preview: 'Waste Management (WM) shares experienced a decline today, underperforming compared to the broader market. The drop was attributed to concerns over ris...',
        stockSymbol: 'WM'},
    {id: 'foghorn-therapeutics-halts-fhd-909-development-aft',
        emoji: '📰',
        title: 'Foghorn Therapeutics Halts FHD-909 Development After Phase 1 Clinical Data Review',
        date: 'Thu, October 1, 2026 at 2:06 PM UTC 4 min read',
        timestamp: '2026-10-01T14:06:53+00:00',
        preview: 'Foghorn Therapeutics has paused the development of its FHD-909 treatment following a review of Phase 1 clinical data, indicating potential concerns re...',
        stockSymbol: 'FHTX'},
    {id: 'illinois-tool-works-itw-buy-sell-or-hold-post-q2-e',
        emoji: '📰',
        title: 'Illinois Tool Works (ITW): Buy, Sell, or Hold Post Q2 Earnings?',
        date: 'Thu, October 1, 2026 at 5:09 PM UTC 3 min read',
        timestamp: '2026-10-01T17:09:07+00:00',
        preview: 'Illinois Tool Works (ITW) recently reported its Q2 earnings, prompting analysts to reassess their recommendations on the stock. The company demonstrat...',
        stockSymbol: 'ITW'},
    {id: 'enovation-controls-a-helios-technologies-operating',
        emoji: '📰',
        title: 'Enovation Controls, a Helios Technologies Operating Company, Earns Three Additional 2026 UK Best Workplaces™ Recognitions',
        date: 'Thu, October 1, 2026 at 1:00 PM UTC 2 min read',
        timestamp: '2026-10-01T13:00:00+00:00',
        preview: 'Enovation Controls, a subsidiary of Helios Technologies (HLIO), has been recognized with three additional accolades in the 2026 UK Best Workplaces™ aw...',
        stockSymbol: 'HLIO'},
    {id: 'better-recession-proof-dividend-stock-kmi-or-oke',
        emoji: '📰',
        title: 'Better Recession-Proof Dividend Stock: KMI or OKE?',
        date: 'Thu, October 1, 2026 at 5:45 PM UTC 3 min read',
        timestamp: '2026-10-01T17:45:13+00:00',
        preview: 'Recent analysis compares Kinder Morgan Inc. (KMI) and OneMain Holdings Inc. (OKE) as potential recession-proof dividend stocks. The discussion highlig...',
        stockSymbol: 'OKE'},
    {id: 'eaton-trades-at-a-premium-to-industry-what-investo',
        emoji: '📰',
        title: 'Eaton Trades at a Premium to Industry: What Investors Should Know',
        date: 'Wed, September 30, 2026 at 4:24 PM UTC 4 min read',
        timestamp: '2026-09-30T16:24:00+00:00',
        preview: 'Eaton Corporation is currently trading at a premium compared to its industry peers, raising questions about its valuation. This premium may reflect in...',
        stockSymbol: 'ETN'},
    {id: 'versant-media-group-inc-s-dividend-analysis',
        emoji: '📰',
        title: 'Versant Media Group Inc\'s Dividend Analysis',
        date: 'Thu, October 1, 2026 at 11:03 AM UTC 3 min read',
        timestamp: '2026-10-01T11:03:36+00:00',
        preview: 'Versant Media Group Inc. has announced a new dividend policy, introducing a quarterly dividend of $0.15 per share. This move is significant for invest...',
        stockSymbol: 'VSNT'},
    {id: 'synopsys-is-becoming-a-major-ai-player-ceo-discuss',
        emoji: '📰',
        title: 'Synopsys is becoming a major AI player: CEO discusses OpenAI, Amazon deals',
        date: 'Thu, October 1, 2026 at 8:27 PM UTC 2 min read',
        timestamp: '2026-10-01T20:27:01+00:00',
        preview: 'Synopsys has positioned itself as a significant player in the artificial intelligence sector, with CEO Aart de Geus highlighting recent collaborations...',
        stockSymbol: 'SNPS'},
    {id: 'avita-medical-rcel-stock-sees-fair-value-lift-afte',
        emoji: '📰',
        title: 'AVITA Medical (RCEL) Stock Sees Fair Value Lift After PermeaDerm Data And Q2 Beat',
        date: 'Thu, October 1, 2026 at 3:09 PM UTC 4 min read',
        timestamp: '2026-10-01T15:09:11+00:00',
        preview: 'AVITA Medical (RCEL) experienced a boost in its stock value following positive data from its PermeaDerm product and a stronger-than-expected Q2 earnin...',
        stockSymbol: 'RCEL'},
    {id: 'american-outdoor-brands-ticks-up-on-10m-buyback-pl',
        emoji: '📰',
        title: 'American Outdoor Brands ticks up on $10M buyback plan',
        date: 'Thu, October 1, 2026 at 9:34 PM UTC 3 min read',
        timestamp: '2026-10-01T21:34:04+00:00',
        preview: 'American Outdoor Brands (AOUT) announced a $10 million share buyback plan, leading to a slight increase in its stock price. This move is significant f...',
        stockSymbol: 'AOUT'},
    {id: 'lockheed-martin-announces-third-quarter-2026-earni',
        emoji: '📰',
        title: 'Lockheed Martin Announces Third Quarter 2026 Earnings Results Webcast',
        date: 'Thu, October 1, 2026 at 1:00 PM UTC 4 min read',
        timestamp: '2026-10-01T13:00:00+00:00',
        preview: 'Lockheed Martin has announced a webcast to discuss its third quarter 2026 earnings results. This event is significant for investors as it will provide...',
        stockSymbol: 'LMT'},
    {id: 'higher-2026-free-cash-flow-guidance-might-change-t',
        emoji: '📰',
        title: 'Higher 2026 Free Cash Flow Guidance Might Change The Case For Investing In ATI (ATI)',
        date: 'Thu, October 1, 2026 at 7:10 AM UTC 3 min read',
        timestamp: '2026-10-01T07:10:25+00:00',
        preview: 'ATI has raised its free cash flow guidance for 2026, signaling stronger financial performance ahead. This adjustment may enhance the investment appeal...',
        stockSymbol: 'ATI'},
    {id: 'core-laboratories-announces-timing-of-third-quarte',
        emoji: '📰',
        title: 'CORE LABORATORIES ANNOUNCES TIMING OF THIRD QUARTER 2026 EARNINGS RELEASE AND CONFERENCE CALL',
        date: 'Thu, October 1, 2026 at 8:15 PM UTC 4 min read',
        timestamp: '2026-10-01T20:15:00+00:00',
        preview: 'Core Laboratories announced the timing for its third quarter 2026 earnings release and subsequent conference call. This update is significant for inve...',
        stockSymbol: 'CLB'},
    {id: 'lucid-group-lcid-beats-stock-market-upswing-what-i',
        emoji: '📰',
        title: 'Lucid Group (LCID) Beats Stock Market Upswing: What Investors Need to Know',
        date: 'Thu, October 1, 2026 at 9:15 PM UTC 2 min read',
        timestamp: '2026-10-01T21:15:02+00:00',
        preview: 'Lucid Group (LCID) outperformed the broader stock market, driven by positive investor sentiment and strong demand for its electric vehicles. This perf...',
        stockSymbol: 'LCID'},
    {id: 'smart-manufacturing-market-forecasts-growth-from-2',
        emoji: '📰',
        title: 'Smart Manufacturing Market Forecasts Growth from $233.33B (2024) to $479.17B by 2029, Profiling Siemens, ABB, Rockwell Automation, IBM & Honeywell',
        date: 'Thu, October 1, 2026 at 8:44 AM UTC 3 min read',
        timestamp: '2026-10-01T08:44:00+00:00',
        preview: 'The smart manufacturing market is projected to grow from $233.33 billion in 2024 to $479.17 billion by 2029, highlighting significant opportunities fo...',
        stockSymbol: 'ROK'},
    {id: 'fresh-data-suggests-upside-to-nvidia-s-hyperscaler',
        emoji: '📰',
        title: 'Fresh data suggests upside to Nvidia’s hyperscaler revenue: Barclays',
        date: 'Thu, October 1, 2026 at 2:05 PM UTC 2 min read',
        timestamp: '2026-10-01T14:05:58+00:00',
        preview: 'Barclays has released new data indicating potential growth in Nvidia\'s hyperscaler revenue, which could positively impact the company\'s financial outl...',
        stockSymbol: 'BARC.L'},
    {id: 'hci-group-hci-falls-more-steeply-than-broader-mark',
        emoji: '📰',
        title: 'HCI Group (HCI) Falls More Steeply Than Broader Market: What Investors Need to Know',
        date: 'Wed, September 30, 2026 at 9:00 PM UTC 3 min read',
        timestamp: '2026-09-30T21:00:04+00:00',
        preview: 'HCI Group (HCI) experienced a significant decline, falling more steeply than the broader market averages. This drop raises concerns for investors rega...',
        stockSymbol: 'HCI'},
    {id: 'workday-s-axe-falls-again-and-this-time-it-lands-o',
        emoji: '📰',
        title: 'Workday\'s axe falls again, and this time it lands on the tech team',
        date: 'Thu, October 1, 2026 at 6:17 PM UTC 4 min read',
        timestamp: '2026-10-01T18:17:00+00:00',
        preview: 'Workday has announced another round of layoffs, impacting its tech team as part of a broader restructuring effort. This move aims to streamline operat...',
        stockSymbol: 'WDAY'},
    {id: 'bank-of-america-s-5-000-gold-forecast-comes-with-a',
        emoji: '📰',
        title: 'Bank of America’s $5,000 gold forecast comes with a warning',
        date: 'Thu, October 1, 2026 at 7:47 PM UTC 3 min read',
        timestamp: '2026-10-01T19:47:00+00:00',
        preview: 'Bank of America has issued a $5,000 gold price forecast, highlighting potential inflation and geopolitical tensions as key drivers. However, the bank ...',
        stockSymbol: 'BAC'},
    {id: 'associated-banc-corp-to-announce-third-quarter-202',
        emoji: '📰',
        title: 'Associated Banc-Corp to Announce Third Quarter 2026 Earnings and Hold Conference Call on October 22, 2026',
        date: 'Thu, October 1, 2026 at 9:00 PM UTC 2 min read',
        timestamp: '2026-10-01T21:00:00+00:00',
        preview: 'Associated Banc-Corp is set to announce its third quarter 2026 earnings on October 22, 2026, followed by a conference call. This event is significant ...',
        stockSymbol: 'ASB'},
    {id: 'constellation-brands-pre-q2-earnings-is-it-poised',
        emoji: '📰',
        title: 'Constellation Brands\' Pre-Q2 Earnings: Is It Poised to Beat Estimates?',
        date: 'Thu, October 1, 2026 at 2:16 PM UTC 3 min read',
        timestamp: '2026-10-01T14:16:00+00:00',
        preview: 'Constellation Brands is set to report its Q2 earnings, with analysts anticipating a potential beat on estimates due to strong demand for its beer and ...',
        stockSymbol: 'STZ'},
    {id: 'panw-stock-rises-21-in-a-month-should-you-hold-or',
        emoji: '📰',
        title: 'PANW Stock Rises 21% in a Month: Should You Hold or Book Profits?',
        date: 'Thu, October 1, 2026 at 2:22 PM UTC 2 min read',
        timestamp: '2026-10-01T14:22:00+00:00',
        preview: 'PANW stock has surged 21% over the past month, reflecting strong investor confidence and positive market sentiment. This significant increase may prom...',
        stockSymbol: 'PANW'},
    {id: 'haemonetics-sets-date-for-publishing-second-quarte',
        emoji: '📰',
        title: 'Haemonetics Sets Date for Publishing Second Quarter Fiscal Year 2027 Results: November 5, 2026',
        date: 'Wed, September 30, 2026 at 8:05 PM UTC 3 min read',
        timestamp: '2026-09-30T20:05:00+00:00',
        preview: 'Haemonetics Corporation has announced that it will release its second quarter fiscal year 2027 results on November 5, 2026. This upcoming earnings rep...',
        stockSymbol: 'HAE'},
    {id: 'why-preferred-bank-pfbc-is-a-great-dividend-stock',
        emoji: '📰',
        title: 'Why Preferred Bank (PFBC) is a Great Dividend Stock Right Now',
        date: 'Wed, September 30, 2026 at 2:45 PM UTC 3 min read',
        timestamp: '2026-09-30T14:45:02+00:00',
        preview: 'Preferred Bank (PFBC) has been highlighted as an attractive dividend stock due to its consistent dividend payments and strong financial performance. T...',
        stockSymbol: 'PFBC'},
    {id: 'texas-instruments-to-webcast-q3-2026-earnings-conf',
        emoji: '📰',
        title: 'Texas Instruments to webcast Q3 2026 earnings conference call',
        date: 'Thu, October 1, 2026 at 2:55 PM UTC 2 min read',
        timestamp: '2026-10-01T14:55:00+00:00',
        preview: 'Texas Instruments has announced it will webcast its Q3 2026 earnings conference call, providing investors with insights into the company\'s financial p...',
        stockSymbol: 'TXN'},
    {id: 'rio-tinto-tasmanian-government-and-commonwealth-go',
        emoji: '📰',
        title: 'Rio Tinto, Tasmanian Government and Commonwealth Government secure the future of Bell Bay Aluminium until 2031',
        date: 'Wed, September 30, 2026 at 9:00 PM UTC 3 min read',
        timestamp: '2026-09-30T21:00:00+00:00',
        preview: 'Rio Tinto, in collaboration with the Tasmanian and Commonwealth Governments, has secured the future of Bell Bay Aluminium until 2031. This agreement e...',
        stockSymbol: 'RIO.AX'},
    {id: 'dental-equipment-technology-stocks-q2-earnings-rev',
        emoji: '📰',
        title: 'Dental Equipment & Technology Stocks Q2 Earnings Review: Envista (NYSE:NVST) Shines',
        date: 'Wed, September 30, 2026 at 7:57 PM UTC 2 min read',
        timestamp: '2026-09-30T19:57:13+00:00',
        preview: 'Envista Holdings Corporation (NYSE: NVST) reported strong Q2 earnings, surpassing analysts\' expectations, driven by robust demand for its dental equip...',
        stockSymbol: 'NVST'},
    {id: 'transunion-announces-earnings-release-date-for-thi',
        emoji: '📰',
        title: 'TransUnion Announces Earnings Release Date for Third Quarter 2026 Results',
        date: 'Thu, October 1, 2026 at 10:50 AM UTC 2 min read',
        timestamp: '2026-10-01T10:50:00+00:00',
        preview: 'TransUnion has announced the release date for its third-quarter 2026 earnings results, which is set for November 3, 2026. This update is significant f...',
        stockSymbol: 'TRU'},
    {id: 'asml-vs-sk-hynix-what-revenue-trends-reveal-to-inv',
        emoji: '📰',
        title: 'ASML vs. SK Hynix: What Revenue Trends Reveal to Investors About These Artificial Intelligence Companies',
        date: 'Thu, October 1, 2026 at 7:37 PM UTC 2 min read',
        timestamp: '2026-10-01T19:37:36+00:00',
        preview: 'ASML and SK Hynix have recently been compared regarding their revenue trends, particularly in the context of the growing artificial intelligence secto...',
        stockSymbol: 'ASML'},
    {id: 'is-teekay-tankers-tnk-a-buy-as-wall-street-analyst',
        emoji: '📰',
        title: 'Is Teekay Tankers (TNK) a Buy as Wall Street Analysts Look Optimistic?',
        date: 'Thu, October 1, 2026 at 12:30 PM UTC 4 min read',
        timestamp: '2026-10-01T12:30:04+00:00',
        preview: 'Teekay Tankers (TNK) has garnered positive attention from Wall Street analysts, who express optimism about the company\'s growth potential. This favora...',
        stockSymbol: 'TNK'},
    {id: 'wells-fargo-bullish-on-bp-downgrades-exxon-mobil-a',
        emoji: '📰',
        title: 'Wells Fargo bullish on BP, downgrades Exxon Mobil amid valuation gap',
        date: 'Thu, October 1, 2026 at 3:35 PM UTC 2 min read',
        timestamp: '2026-10-01T15:35:44+00:00',
        preview: 'Wells Fargo has downgraded Exxon Mobil (XOM) due to concerns over its valuation compared to peers, particularly BP, which the firm remains bullish on....',
        stockSymbol: 'XOM'},
    {id: 'conagra-brands-fiscal-q1-eps-beat-led-by-slightly',
        emoji: '📰',
        title: 'Conagra Brands\' Fiscal Q1 EPS Beat Led by Slightly Better Sales, Lower Inflation, UBS Says',
        date: 'Thu, October 1, 2026 at 3:53 PM UTC 3 min read',
        timestamp: '2026-10-01T15:53:14+00:00',
        preview: 'Conagra Brands reported a stronger-than-expected fiscal Q1 earnings per share (EPS), driven by slightly improved sales and lower inflation, according ...',
        stockSymbol: 'CAG'},
    {id: 'nutanix-ntnx-stock-may-be-12-undervalued-as-manage',
        emoji: '📰',
        title: 'Nutanix (NTNX) Stock May Be 12% Undervalued As Managed Cloud Expands',
        date: 'Thu, October 1, 2026 at 11:10 PM UTC 3 min read',
        timestamp: '2026-10-01T23:10:40+00:00',
        preview: 'Nutanix (NTNX) stock is currently considered approximately 12% undervalued, according to recent analysis, as the managed cloud market continues to exp...',
        stockSymbol: 'NTNX'},
    {id: 'amazon-amzn-and-goodrx-gdrx-chase-prescription-sub',
        emoji: '📰',
        title: 'Amazon (AMZN) and GoodRx (GDRX) Chase Prescription Subscribers as Insurance Coverage Slips',
        date: 'Thu, October 1, 2026 at 8:38 PM UTC 4 min read',
        timestamp: '2026-10-01T20:38:53+00:00',
        preview: 'Amazon and GoodRx are intensifying their efforts to attract prescription subscribers amid a decline in insurance coverage for medications. This shift ...',
        stockSymbol: 'GDRX'},
    {id: 'all-you-need-to-know-about-ametek-ame-rating-upgra',
        emoji: '📰',
        title: 'All You Need to Know About Ametek (AME) Rating Upgrade to Buy',
        date: 'Thu, October 1, 2026 at 3:00 PM UTC 2 min read',
        timestamp: '2026-10-01T15:00:01+00:00',
        preview: 'Ametek (AME) received a rating upgrade to "Buy" from a prominent financial institution, reflecting increased confidence in the company\'s growth potent...',
        stockSymbol: 'AME'},
    {id: 'advanced-micro-devices-amd-could-be-33-undervalued',
        emoji: '📰',
        title: 'Advanced Micro Devices (AMD) Could Be 33% Undervalued Following Its World Labs Deal',
        date: 'Thu, October 1, 2026 at 5:10 PM UTC 3 min read',
        timestamp: '2026-10-01T17:10:50+00:00',
        preview: 'Advanced Micro Devices (AMD) recently announced a strategic deal with World Labs, which analysts believe could position the company as 33% undervalued...',
        stockSymbol: 'AMD'},
    {id: 'netapp-unveils-novus-ai-data-engine-upgrades-to-po',
        emoji: '📰',
        title: 'NetApp Unveils Novus, AI Data Engine Upgrades to Power Agentic AI',
        date: 'Thu, October 1, 2026 at 12:02 AM UTC 2 min read',
        timestamp: '2026-10-01T00:02:20+00:00',
        preview: 'NetApp has launched Novus, an upgraded AI data engine designed to enhance its capabilities in powering agentic AI applications. This development is si...',
        stockSymbol: 'NTAP'},
    {id: 'kulr-secures-over-1-million-in-battery-purchase-or',
        emoji: '📰',
        title: 'KULR Secures Over $1 Million in Battery Purchase Orders Supporting Drone Dominance Program',
        date: 'Thu, October 1, 2026 at 12:30 PM UTC 2 min read',
        timestamp: '2026-10-01T12:30:00+00:00',
        preview: 'KULR Technology has secured over $1 million in battery purchase orders to support its Drone Dominance Program. This development is significant for inv...',
        stockSymbol: 'KULR'},
    {id: 'albemarle-corporation-to-release-third-quarter-202',
        emoji: '📰',
        title: 'Albemarle Corporation to Release Third Quarter 2026 Earnings Results on Wednesday, November 4, 2026',
        date: 'Thu, October 1, 2026 at 8:15 PM UTC 3 min read',
        timestamp: '2026-10-01T20:15:00+00:00',
        preview: 'Albemarle Corporation has announced that it will release its third quarter 2026 earnings results on Wednesday, November 4, 2026. This upcoming earning...',
        stockSymbol: 'ALB'},
    {id: 'mckesson-mck-sees-a-more-significant-dip-than-broa',
        emoji: '📰',
        title: 'McKesson (MCK) Sees a More Significant Dip Than Broader Market: Some Facts to Know',
        date: 'Wed, September 30, 2026 at 9:00 PM UTC 3 min read',
        timestamp: '2026-09-30T21:00:04+00:00',
        preview: 'McKesson (MCK) experienced a notable decline in its stock price, falling more sharply than the broader market. This dip raises concerns for investors,...',
        stockSymbol: 'MCK'},
    {id: 'telos-corporation-wins-new-xacta-contract-with-u-s',
        emoji: '📰',
        title: 'Telos Corporation Wins New Xacta Contract with U.S. Department of Commerce Office of Inspector General',
        date: 'Thu, October 1, 2026 at 5:30 PM UTC 2 min read',
        timestamp: '2026-10-01T17:30:00+00:00',
        preview: 'Telos Corporation has secured a new contract for its Xacta cybersecurity platform with the U.S. Department of Commerce Office of Inspector General. Th...',
        stockSymbol: 'TLS'},
    {id: 'louisiana-pacific-lpx-sees-a-more-significant-dip',
        emoji: '📰',
        title: 'Louisiana-Pacific (LPX) Sees a More Significant Dip Than Broader Market: Some Facts to Know',
        date: 'Wed, September 30, 2026 at 9:00 PM UTC 4 min read',
        timestamp: '2026-09-30T21:00:05+00:00',
        preview: 'Louisiana-Pacific Corporation (LPX) experienced a notable decline in its stock price, surpassing the broader market\'s downturn. This dip is attributed...',
        stockSymbol: 'LPX'},
    {id: 'ck-infrastructure-holdings-sehk-1038-stock-could-b',
        emoji: '📰',
        title: 'CK Infrastructure Holdings (SEHK:1038) Stock Could Be Overvalued Despite Steady Earnings',
        date: 'Thu, October 1, 2026 at 6:09 PM UTC 3 min read',
        timestamp: '2026-10-01T18:09:38+00:00',
        preview: 'CK Infrastructure Holdings (SEHK: 1038) is facing scrutiny as analysts suggest the stock may be overvalued despite its consistent earnings performance...',
        stockSymbol: '1038.HK'},
    {id: 'why-is-medtronic-mdt-down-6-4-since-last-earnings',
        emoji: '📰',
        title: 'Why Is Medtronic (MDT) Down 6.4% Since Last Earnings Report?',
        date: 'Thu, October 1, 2026 at 2:30 PM UTC 3 min read',
        timestamp: '2026-10-01T14:30:04+00:00',
        preview: 'Medtronic (MDT) has seen a 6.4% decline in its stock price since its last earnings report, primarily due to concerns over slower-than-expected revenue...',
        stockSymbol: 'MDT'},
    {id: 'eldorado-gold-nears-production-milestones-as-skour',
        emoji: '📰',
        title: 'Eldorado Gold Nears Production Milestones as Skouries, McIlvenna Bay Near Launch',
        date: 'Thu, October 1, 2026 at 4:02 AM UTC 2 min read',
        timestamp: '2026-10-01T04:02:10+00:00',
        preview: 'Eldorado Gold Corporation (ELD.TO) is approaching significant production milestones with its Skouries and McIlvenna Bay projects nearing launch. This ...',
        stockSymbol: 'ELD.TO'},
    {id: 'fortinet-launches-p-a-u-s-e-a-free-national-campai',
        emoji: '📰',
        title: 'Fortinet Launches P.A.U.S.E., a Free National Campaign Helping Canadians Stop and Think Before AI-Driven Scams Succeed',
        date: 'Thu, October 1, 2026 at 1:02 PM UTC 3 min read',
        timestamp: '2026-10-01T13:02:00+00:00',
        preview: 'Fortinet has launched P.A.U.S.E., a free national campaign aimed at educating Canadians on recognizing and preventing AI-driven scams. This initiative...',
        stockSymbol: 'FTNT'},
    {id: 'kimberly-clark-kmb-launches-exchange-offers-for-ou',
        emoji: '📰',
        title: 'Kimberly Clark (KMB) Launches Exchange Offers For Outstanding Notes',
        date: 'Wed, September 30, 2026 at 10:08 PM UTC 3 min read',
        timestamp: '2026-09-30T22:08:23+00:00',
        preview: 'Kimberly Clark (KMB) has initiated exchange offers for its outstanding notes, allowing bondholders to exchange their existing securities for new ones....',
        stockSymbol: 'KMB'},
    {id: 'e-trade-from-morgan-stanley-releases-monthly-secto',
        emoji: '📰',
        title: 'E*TRADE from Morgan Stanley Releases Monthly Sector Rotation Study',
        date: 'Thu, October 1, 2026 at 8:00 PM UTC 2 min read',
        timestamp: '2026-10-01T20:00:00+00:00',
        preview: 'Morgan Stanley\'s E*TRADE has released its latest Monthly Sector Rotation Study, providing insights into shifting market trends and sector performance....',
        stockSymbol: 'MS'},
    {id: 'cousins-properties-announces-dates-for-third-quart',
        emoji: '📰',
        title: 'Cousins Properties Announces Dates for Third Quarter 2026 Earnings Release and Conference Call',
        date: 'Thu, October 1, 2026 at 8:15 PM UTC 4 min read',
        timestamp: '2026-10-01T20:15:00+00:00',
        preview: 'Cousins Properties has announced the dates for its third quarter 2026 earnings release and conference call, scheduled for November 1, 2026. This updat...',
        stockSymbol: 'CUZ'},
    {id: 'nike-stock-sinks-as-revenue-misses-estimates',
        emoji: '🔴',
        title: 'Nike stock sinks as revenue misses estimates',
        date: 'Thu, October 1, 2026 at 8:58 PM UTC 3 min read',
        timestamp: '2026-10-01T20:58:07+00:00',
        preview: 'Nike\'s stock experienced a significant decline following the release of its latest earnings report, which revealed that revenue fell short of analysts...',
        stockSymbol: '',
        link: ''},
    {id: 'transunion-announces-earnings-release-date-for-thi',
        emoji: '📰',
        title: 'TransUnion Announces Earnings Release Date for Third Quarter 2026 Results',
        date: 'Thu, October 1, 2026 at 10:50 AM UTC 3 min read',
        timestamp: '2026-10-01T10:50:00+00:00',
        preview: 'TransUnion has announced that it will release its earnings results for the third quarter of 2026 on November 3, 2026. Investors will be keenly watchin...',
        stockSymbol: '',
        link: ''},
    {id: 'cleveland-cliffs-to-announce-third-quarter-2026-ea',
        emoji: '📰',
        title: 'Cleveland-Cliffs to Announce Third-Quarter 2026 Earnings Results and Host Conference Call on October 19',
        date: 'Thu, October 1, 2026 at 8:15 PM UTC 3 min read',
        timestamp: '2026-10-01T20:15:00+00:00',
        preview: 'Cleveland-Cliffs Inc. is set to announce its third-quarter 2026 earnings results on October 19, 2026, followed by a conference call to discuss the fin...',
        stockSymbol: '',
        link: ''},
    {id: 'fed-s-cook-inflation-has-been-too-high-for-too-lon',
        emoji: '📊',
        title: 'Fed\'s Cook: inflation has been too high for too long - reuters.com',
        date: 'Wed, September 30, 2026 at 7:28 PM UTC 3 min read',
        timestamp: '2026-09-30T19:28:23+00:00',
        preview: 'In a recent statement, Federal Reserve Governor Lisa Cook emphasized that inflation has remained excessively high for an extended period, prompting co...',
        stockSymbol: '',
        link: ''},
    {id: 'neel-kashkari-q-a-at-the-council-on-foreign-relati',
        emoji: '📰',
        title: 'Neel Kashkari Q&A at the Council on Foreign Relations',
        date: 'Wed, September 30, 2026 at 10:00 PM UTC 3 min read',
        timestamp: '2026-09-30T22:00:00+00:00',
        preview: 'In a recent Q&A session at the Council on Foreign Relations, Neel Kashkari, President of the Federal Reserve Bank of Minneapolis, discussed the curren...',
        stockSymbol: '',
        link: ''},
    {id: 'albertsons-companies-announces-second-quarter-fisc',
        emoji: '📰',
        title: 'Albertsons Companies Announces Second Quarter Fiscal 2026 Earnings Release and Conference Call Date',
        date: 'Tue, September 29, 2026 at 8:05 PM UTC 3 min read',
        timestamp: '2026-09-29T20:05:53+00:00',
        preview: 'Albertsons Companies has announced the release date for its second quarter fiscal 2026 earnings report, scheduled for June 15, 2026. The company will ...',
        stockSymbol: '',
        link: ''},
    {id: 'federal-reserve-staffer-removed-sensitive-files-be',
        emoji: '📊',
        title: 'Federal Reserve Staffer Removed Sensitive Files Before Retiring, Report Finds',
        date: 'Mon, September 28, 2026 at 4:54 PM UTC 3 min read',
        timestamp: '2026-09-28T16:54:00+00:00',
        preview: 'A recent report from the Wall Street Journal reveals that a Federal Reserve staffer removed sensitive files prior to their retirement, raising concern...',
        stockSymbol: '',
        link: ''},
    {id: 'monetary-policy-overtakes-inflation-as-cfos-top-co',
        emoji: '📊',
        title: 'Monetary policy overtakes inflation as CFOs top concern',
        date: 'Mon, September 28, 2026 at 5:51 PM UTC 3 min read',
        timestamp: '2026-09-28T17:51:04+00:00',
        preview: 'In a recent survey, Chief Financial Officers (CFOs) have identified monetary policy as their primary concern, surpassing inflation for the first time ...',
        stockSymbol: '',
        link: ''},
    {id: 'key-us-data-this-week-seen-bolstering-case-for-oct',
        emoji: '📊',
        title: 'Key US Data This Week Seen Bolstering Case for October Rate Hike - Bloomberg.com',
        date: 'Mon, September 28, 2026 at 10:00 AM UTC 3 min read',
        timestamp: '2026-09-28T10:00:00+00:00',
        preview: 'This week, key U.S. economic data is anticipated to strengthen the argument for an interest rate hike by the Federal Reserve in October. Analysts are ...',
        stockSymbol: '',
        link: ''},
    {id: 'we-re-witnessing-the-stock-market-do-something-for',
        emoji: '📰',
        title: 'We\'re Witnessing the Stock Market Do Something for Only the 3rd Time in 156 Years, and History Is Crystal Clear About What\'s Next for Stocks',
        date: 'Sun, September 27, 2026 at 10:57 AM UTC 3 min read',
        timestamp: '2026-09-27T10:57:59+00:00',
        preview: 'The stock market is currently experiencing a rare phenomenon, occurring for only the third time in 156 years, which could have significant implication...',
        stockSymbol: '',
        link: ''},
    {id: 'prediction-a-stock-market-crash-is-coming-heres-th',
        emoji: '🔴',
        title: 'Prediction: A Stock Market Crash Is Coming. Heres the One Move You Should Make, According to History.',
        date: 'Sun, September 27, 2026 at 12:05 PM UTC 3 min read',
        timestamp: '2026-09-27T12:05:00+00:00',
        preview: 'A recent article from The Motley Fool warns that a stock market crash may be on the horizon, drawing on historical trends to support this prediction. ...',
        stockSymbol: '',
        link: ''},
    {id: 'silgan-to-release-third-quarter-2026-earnings-resu',
        emoji: '📰',
        title: 'Silgan to Release Third Quarter 2026 Earnings Results on October 29, 2026',
        date: 'Fri, September 25, 2026 at 9:20 PM UTC 3 min read',
        timestamp: '2026-09-25T21:20:00+00:00',
        preview: 'Silgan Holdings Inc. has announced that it will release its third quarter 2026 earnings results on October 29, 2026. Investors will be keenly watching...',
        stockSymbol: '',
        link: ''},
    {id: 'reducing-environmental-hazards-in-k12-schools-can',
        emoji: '📰',
        title: 'Reducing Environmental Hazards In K12 Schools Can Boost Students Lifetime Earnings - urban.org',
        date: 'Fri, September 25, 2026 at 12:00 PM UTC 3 min read',
        timestamp: '2026-09-25T12:00:00+00:00',
        preview: 'A recent study by Urban Institute highlights that reducing environmental hazards in K-12 schools can significantly enhance students\' lifetime earnings...',
        stockSymbol: '',
        link: ''},
    {id: 'micron-technology-stock-wavers-ahead-of-fiscal-q4',
        emoji: '📰',
        title: 'Micron Technology Stock Wavers Ahead Of Fiscal Q4 Earnings Report - Investor\'s Business Daily',
        date: 'Fri, September 25, 2026 at 8:20 PM UTC 3 min read',
        timestamp: '2026-09-25T20:20:00+00:00',
        preview: 'Micron Technology\'s stock has shown volatility as investors await its fiscal Q4 earnings report, scheduled for release on September 28. The semiconduc...',
        stockSymbol: '',
        link: ''},
    {id: 'fed-s-williams-says-it-is-reasonable-to-see-anothe',
        emoji: '📊',
        title: 'Fed\'s Williams says it is reasonable to see another US rate hike this year',
        date: 'Thu, September 24, 2026 at 2:17 PM UTC 3 min read',
        timestamp: '2026-09-24T14:17:57+00:00',
        preview: 'In a recent statement, Federal Reserve Bank of New York President John Williams indicated that it is reasonable to anticipate another interest rate hi...',
        stockSymbol: '',
        link: ''},
    {id: 'rising-treasury-yields-could-push-car-loan-rates-h',
        emoji: '📊',
        title: 'Rising Treasury yields could push car loan rates higher, experts say. What buyers need to know',
        date: 'Thu, September 24, 2026 at 4:14 PM UTC 3 min read',
        timestamp: '2026-09-24T16:14:35+00:00',
        preview: 'Rising Treasury yields are expected to lead to higher car loan rates, according to financial experts. As the yield on the 10-year Treasury note has re...',
        stockSymbol: '',
        link: ''},
    {id: 'commentary-passive-investing-that-s-p-500-index-fu',
        emoji: '📰',
        title: 'COMMENTARY: Passive investing? That S&P 500 index fund is basically a tech fund',
        date: 'Wed, September 23, 2026 at 11:40 PM UTC 3 min read',
        timestamp: '2026-09-23T23:40:35+00:00',
        preview: 'The S&P 500 index, often viewed as a benchmark for passive investing, has increasingly become dominated by technology stocks. As of recent data, tech ...',
        stockSymbol: '',
        link: ''},
    {id: 'dow-jones-futures-fall-after-nasdaq-hits-new-high',
        emoji: '🔴',
        title: 'Dow Jones Futures Fall After Nasdaq Hits New High; Sandisk, Micron Trigger Buy Signals - Investor\'s Business Daily',
        date: 'Wed, September 23, 2026 at 12:05 PM UTC 3 min read',
        timestamp: '2026-09-23T12:05:00+00:00',
        preview: 'Dow Jones futures experienced a decline following the Nasdaq\'s recent surge to a new record high, reflecting a mixed sentiment in the market. Notably,...',
        stockSymbol: '',
        link: ''},
    {id: '5-things-to-know-before-the-stock-market-opens-on',
        emoji: '📰',
        title: '5 Things to Know Before the Stock Market Opens on Wednesday',
        date: 'Wed, September 23, 2026 at 12:18 PM UTC 3 min read',
        timestamp: '2026-09-23T12:18:54+00:00',
        preview: 'As the stock market prepares to open on Wednesday, investors should be aware of several key developments. Notably, major indices are poised for a mixe...',
        stockSymbol: '',
        link: ''},
    {id: 'anthropic-ipo-what-10b5-1-plans-mean-for-employees',
        emoji: '📰',
        title: 'Anthropic IPO: What 10b5-1 Plans Mean For Employees',
        date: 'Tue, September 22, 2026 at 8:28 PM UTC 3 min read',
        timestamp: '2026-09-22T20:28:18+00:00',
        preview: 'Anthropic, an AI research company, is preparing for its initial public offering (IPO) and has implemented 10b5-1 plans to facilitate stock sales for e...',
        stockSymbol: '',
        link: ''}
];

// Render news items into the sidebar
function renderNewsItems() {
    const container = document.getElementById('news-items');
    if (!container) return;
    
    // Sort all items by date (newest first)
    const sortedItems = [...newsItems].sort((a, b) => {
        const dateA = new Date(a.date);
        const dateB = new Date(b.date);
        return dateB - dateA;
    });
    
    // Separate stock news and general news from sorted items
    const stockNews = sortedItems.filter(item => item.stockSymbol);
    const generalNews = sortedItems.filter(item => !item.stockSymbol);
    
    // Show 1 general + 4 stock news
    const displayItems = [];
    if (generalNews.length > 0) displayItems.push(generalNews[0]);
    displayItems.push(...stockNews.slice(0, 4));
    
    container.innerHTML = displayItems.map(item => {
        const url = item.stockSymbol ? `stocks/${item.stockSymbol}.html` : `news.html#${item.id}`;
        return `
        <div class="news-item" style="padding: 8px; margin-bottom: 8px; border-bottom: 1px solid var(--border-color); cursor: pointer;" onclick="window.location.href='${url}'">
            <div style="font-weight: 600; color: var(--text-primary); font-size: 0.85rem; margin-bottom: 3px;">${item.emoji} ${item.title}</div>
            <div style="color: var(--text-secondary); font-size: 0.7rem; margin-bottom: 2px;" data-timestamp="${item.timestamp || ''}" class="article-date">${item.date}</div>
            <div style="color: var(--text-secondary); font-size: 0.75rem; line-height: 1.3;">${item.preview}</div>
        </div>
        `;
    }).join('');
}

if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', renderNewsItems);
} else {
    renderNewsItems();
}
