// Shared news items for Market News sidebar
const newsItems = [
    {
        id: 'uipath-expands-partnership-with-bdo-to-build-agent',
        emoji: '📰',
        title: 'UiPath Expands Partnership With BDO To Build Agentic AI Solutions',
        date: 'Wed, September 30, 2026 at 11:47 AM UTC 3 min read',
        timestamp: '2026-09-30T11:47:20+00:00',
        preview: 'UiPath has announced an expansion of its partnership with BDO to develop advanced agentic AI solutions. This collaboration aims to enhance automation ...',
        stockSymbol: 'PATH'
    },
    {
        id: 'ge-healthcare-gehc-upgraded-to-buy-here-s-why',
        emoji: '📰',
        title: 'GE HealthCare (GEHC) Upgraded to Buy: Here\'s Why',
        date: 'Wed, September 30, 2026 at 3:00 PM UTC 2 min read',
        timestamp: '2026-09-30T15:00:03+00:00',
        preview: 'GE HealthCare (GEHC) has been upgraded to a "Buy" rating by analysts, reflecting positive sentiment regarding its growth potential and market position...',
        stockSymbol: 'GEHC'
    },
    {
        id: 'cava-group-cava-rises-as-market-takes-a-dip-key-fa',
        emoji: '📰',
        title: 'Cava Group (CAVA) Rises As Market Takes a Dip: Key Facts',
        date: 'Wed, September 30, 2026 at 8:50 PM UTC 2 min read',
        timestamp: '2026-09-30T20:50:03+00:00',
        preview: 'Cava Group (CAVA) saw its stock price increase despite a broader market decline, highlighting its resilience in a challenging economic environment. Th...',
        stockSymbol: 'CAVA'},
    {id: 'paychex-just-fell-14-how-does-its-dividend-stack-u',
        emoji: '📰',
        title: 'Paychex Just Fell 14%. How Does Its Dividend Stack Up Against ADP?',
        date: 'Tue, September 29, 2026 at 2:37 PM UTC 2 min read',
        timestamp: '2026-09-29T14:37:31+00:00',
        preview: 'Paychex shares dropped 14% following a disappointing earnings report, raising concerns about its growth prospects compared to competitors like ADP. Th...',
        stockSymbol: 'PAYX'},
    {id: 'at-t-ceo-says-elon-musk-s-spacex-phone-strategy-no',
        emoji: '📰',
        title: 'AT&T CEO says Elon Musk\'s SpaceX phone strategy not "viable"',
        date: 'Tue, September 29, 2026 at 7:16 PM UTC 2 min read',
        timestamp: '2026-09-29T19:16:32+00:00',
        preview: 'AT&T CEO John Stankey has criticized Elon Musk\'s SpaceX phone strategy, deeming it "not viable." This statement highlights potential challenges for Sp...',
        stockSymbol: 'T'},
    {id: 'why-vici-s-1-3x-dividend-coverage-ratio-looks-safe',
        emoji: '📰',
        title: 'Why VICI’s 1.3x Dividend Coverage Ratio Looks Safer Than Its Falling Stock Price Suggests',
        date: 'Wed, September 30, 2026 at 2:45 PM UTC 4 min read',
        timestamp: '2026-09-30T14:45:53+00:00',
        preview: 'VICI Properties reported a dividend coverage ratio of 1.3x, indicating that its earnings sufficiently cover its dividend payments despite a recent dec...',
        stockSymbol: 'VICI'},
    {id: 'is-coherent-s-photonlink-push-reframing-its-ai-dat',
        emoji: '📰',
        title: 'Is Coherent\'s PhotonLink Push Reframing Its AI Datacenter Optics Edge For Investors (COHR)?',
        date: 'Wed, September 30, 2026 at 3:09 PM UTC 4 min read',
        timestamp: '2026-09-30T15:09:12+00:00',
        preview: 'Coherent (COHR) has introduced its PhotonLink technology, aimed at enhancing optical connectivity in AI datacenters. This development is significant f...',
        stockSymbol: 'COHR'},
    {id: 'why-archer-daniels-midland-adm-dipped-more-than-br',
        emoji: '📰',
        title: 'Why Archer Daniels Midland (ADM) Dipped More Than Broader Market Today',
        date: 'Tue, September 29, 2026 at 9:00 PM UTC 3 min read',
        timestamp: '2026-09-29T21:00:02+00:00',
        preview: 'Archer Daniels Midland (ADM) experienced a decline that outpaced the broader market today, primarily due to concerns over rising input costs and poten...',
        stockSymbol: 'ADM'},
    {id: 'cheniere-energy-s-petrobras-lng-deal-supports-long',
        emoji: '📰',
        title: 'Cheniere Energy\'s Petrobras LNG Deal Supports Long-Term Growth',
        date: 'Wed, September 30, 2026 at 12:26 PM UTC 4 min read',
        timestamp: '2026-09-30T12:26:00+00:00',
        preview: 'Cheniere Energy has secured a long-term liquefied natural gas (LNG) supply agreement with Petrobras, enhancing its position in the global energy marke...',
        stockSymbol: 'LNG'},
    {id: 'lineage-and-bsf-extend-25-year-relationship-based',
        emoji: '📰',
        title: 'Lineage and BSF Extend 25-Year Relationship Based on Trust and Innovation',
        date: 'Tue, September 29, 2026 at 6:10 PM UTC 4 min read',
        timestamp: '2026-09-29T18:10:00+00:00',
        preview: 'Lineage Logistics and BSF have renewed their partnership for another 25 years, emphasizing their commitment to trust and innovation in the supply chai...',
        stockSymbol: 'LINE'},
    {id: 'cipher-digital-slips-3-despite-20-year-barber-lake',
        emoji: '📰',
        title: 'Cipher Digital Slips 3% Despite 20-year Barber Lake Lease Extension; TeraWulf Retreats 2%, IREN Limited Treads Water',
        date: 'Wed, September 30, 2026 at 4:17 PM UTC 2 min read',
        timestamp: '2026-09-30T16:17:48+00:00',
        preview: 'TeraWulf (WULF) shares fell 2% following news of a 20-year lease extension for Barber Lake, despite the positive implications for long-term operations...',
        stockSymbol: 'WULF'},
    {id: 'circle-crcl-stock-looks-fairly-valued-despite-fres',
        emoji: '📰',
        title: 'Circle (CRCL) Stock Looks Fairly Valued Despite Fresh USDC Partnership News',
        date: 'Wed, September 30, 2026 at 4:11 PM UTC 3 min read',
        timestamp: '2026-09-30T16:11:47+00:00',
        preview: 'Circle (CRCL) stock is currently viewed as fairly valued following the announcement of a new partnership involving USDC, a stablecoin that the company...',
        stockSymbol: 'CRCL'},
    {id: 'this-analyst-just-downgraded-moderna-stock-here-s',
        emoji: '📰',
        title: 'This Analyst Just Downgraded Moderna Stock. Here\'s Why.',
        date: 'Wed, September 30, 2026 at 8:40 PM UTC 4 min read',
        timestamp: '2026-09-30T20:40:57+00:00',
        preview: 'Moderna\'s stock was recently downgraded by an analyst, citing concerns over declining demand for its COVID-19 vaccines as the pandemic situation evolv...',
        stockSymbol: 'MRNA'},
    {id: 'saic-saic-up-1-1-since-last-earnings-report-can-it',
        emoji: '📰',
        title: 'SAIC (SAIC) Up 1.1% Since Last Earnings Report: Can It Continue?',
        date: 'Wed, September 30, 2026 at 2:30 PM UTC 2 min read',
        timestamp: '2026-09-30T14:30:01+00:00',
        preview: 'SAIC\'s stock has risen 1.1% since its last earnings report, reflecting a positive market response to its financial performance. This uptick is signifi...',
        stockSymbol: 'SAIC'},
    {id: 'acm-research-announces-participation-in-18th-annua',
        emoji: '📰',
        title: 'ACM Research Announces Participation in 18th Annual CEO Investor Summit 2026',
        date: 'Wed, September 30, 2026 at 8:05 PM UTC 4 min read',
        timestamp: '2026-09-30T20:05:00+00:00',
        preview: 'ACM Research has announced its participation in the 18th Annual CEO Investor Summit scheduled for 2026. This event provides a platform for the company...',
        stockSymbol: 'ACMR'},
    {id: 'why-eagle-bancorp-montana-inc-ebmt-is-a-top-divide',
        emoji: '📰',
        title: 'Why Eagle Bancorp Montana, Inc. (EBMT) is a Top Dividend Stock for Your Portfolio',
        date: 'Wed, September 30, 2026 at 2:45 PM UTC 4 min read',
        timestamp: '2026-09-30T14:45:04+00:00',
        preview: 'Eagle Bancorp Montana, Inc. (EBMT) has been highlighted as a top dividend stock due to its consistent dividend payments and strong financial performan...',
        stockSymbol: 'EBMT'},
    {id: 'bristol-myers-squibb-s-dividend-sustainability-hin',
        emoji: '📰',
        title: 'Bristol Myers Squibb’s Dividend Sustainability Hinges on One Critical Cash Flow Metric',
        date: 'Wed, September 30, 2026 at 3:45 PM UTC 3 min read',
        timestamp: '2026-09-30T15:45:53+00:00',
        preview: 'Bristol Myers Squibb\'s recent analysis highlights that the sustainability of its dividend is heavily reliant on a key cash flow metric. This developme...',
        stockSymbol: 'BMY'},
    {id: 'norwegian-cruise-line-sees-third-quarter-results-t',
        emoji: '📰',
        title: 'Norwegian Cruise Line sees third-quarter results topping guidance',
        date: 'Wed, September 30, 2026 at 2:22 PM UTC 4 min read',
        timestamp: '2026-09-30T14:22:00+00:00',
        preview: 'Norwegian Cruise Line Holdings (NCLH) reported third-quarter results that exceeded analysts\' expectations, driven by strong demand for cruise bookings...',
        stockSymbol: 'NCLH'},
    {id: 'bank-ozk-announces-third-quarter-2026-earnings-rel',
        emoji: '📰',
        title: 'Bank OZK Announces Third Quarter 2026 Earnings Release and Conference Call Dates',
        date: 'Wed, September 30, 2026 at 8:01 PM UTC 2 min read',
        timestamp: '2026-09-30T20:01:00+00:00',
        preview: 'Bank OZK has announced the release date for its third quarter 2026 earnings report, along with the schedule for an accompanying conference call. This ...',
        stockSymbol: 'OZK'},
    {id: 'the-zacks-analyst-blog-highlights-phillips-66-hf-s',
        emoji: '📰',
        title: 'The Zacks Analyst Blog Highlights Phillips 66, HF Sinclair and Eni',
        date: 'Wed, September 30, 2026 at 11:55 AM UTC 3 min read',
        timestamp: '2026-09-30T11:55:00+00:00',
        preview: 'The Zacks Analyst Blog has highlighted Phillips 66, HF Sinclair, and Eni, indicating positive analyst sentiment towards these energy stocks. This reco...',
        stockSymbol: 'PSX'},
    {id: 'david-stinnett-purchases-27-000-karman-holdings-sh',
        emoji: '📰',
        title: 'David Stinnett Purchases 27,000 Karman Holdings Shares for $1 Million. Is the Defense Contractor Now a Buy?',
        date: 'Tue, September 29, 2026 at 10:07 PM UTC 3 min read',
        timestamp: '2026-09-29T22:07:01+00:00',
        preview: 'David Stinnett has acquired 27,000 shares of Karman Holdings for $1 million, signaling potential confidence in the defense contractor\'s future perform...',
        stockSymbol: 'KRMN'},
    {id: 'chargepoint-climbs-6-extends-65-monthly-run-evgo-i',
        emoji: '📰',
        title: 'ChargePoint Climbs 6%, Extends 65% Monthly Run; EVgo Inches Higher, Blink Charging Slips',
        date: 'Tue, September 29, 2026 at 4:52 PM UTC 4 min read',
        timestamp: '2026-09-29T16:52:42+00:00',
        preview: 'EVgo\'s stock saw a modest increase as ChargePoint\'s shares surged 6%, marking a 65% rise over the past month. This uptick in EVgo\'s stock reflects gro...',
        stockSymbol: 'EVGO'},
    {id: 'are-investors-undervaluing-magna-international-mga',
        emoji: '📰',
        title: 'Are Investors Undervaluing Magna International (MGA) Right Now?',
        date: 'Wed, September 30, 2026 at 12:40 PM UTC 2 min read',
        timestamp: '2026-09-30T12:40:02+00:00',
        preview: 'Recent analysis suggests that Magna International (MG.TO) may be undervalued, prompting investors to reassess its stock potential. The company\'s stron...',
        stockSymbol: 'MG.TO'},
    {id: 'amphenol-aph-beat-expectations-is-the-stock-still',
        emoji: '📰',
        title: 'Amphenol (APH) Beat Expectations, Is The Stock Still Cheap?',
        date: 'Wed, September 30, 2026 at 12:10 PM UTC 2 min read',
        timestamp: '2026-09-30T12:10:42+00:00',
        preview: 'Amphenol (APH) reported earnings that surpassed analysts\' expectations, indicating strong demand for its connectors and interconnect systems. This pos...',
        stockSymbol: 'APH'},
    {id: 'northern-trust-initiates-record-breaking-mutual-fu',
        emoji: '📰',
        title: 'Northern Trust Initiates Record-Breaking Mutual-Fund-to-ETF Conversion',
        date: 'Tue, September 29, 2026 at 7:05 PM UTC 2 min read',
        timestamp: '2026-09-29T19:05:46+00:00',
        preview: 'Northern Trust has announced a record-breaking conversion of its mutual funds into exchange-traded funds (ETFs), marking a significant shift in its in...',
        stockSymbol: 'NTRS'},
    {id: 'what-to-expect-from-ge-aerospace-s-q3-2026-earning',
        emoji: '📰',
        title: 'What to Expect From GE Aerospace\'s Q3 2026 Earnings Report',
        date: 'Wed, September 30, 2026 at 6:30 PM UTC 3 min read',
        timestamp: '2026-09-30T18:30:51+00:00',
        preview: 'GE Aerospace is set to release its Q3 2026 earnings report, with analysts anticipating strong revenue growth driven by increased demand for commercial...',
        stockSymbol: 'GE'},
    {id: 'synchrony-financial-syf-could-be-20-below-fair-val',
        emoji: '📰',
        title: 'Synchrony Financial (SYF) Could Be 20% Below Fair Value Following Vetspire Partnership',
        date: 'Wed, September 30, 2026 at 8:11 PM UTC 3 min read',
        timestamp: '2026-09-30T20:11:52+00:00',
        preview: 'Synchrony Financial (SYF) has entered a partnership with Vetspire, a veterinary software company, which analysts believe could position the stock appr...',
        stockSymbol: 'SYF'},
    {id: 'why-waste-management-wm-dipped-more-than-broader-m',
        emoji: '📰',
        title: 'Why Waste Management (WM) Dipped More Than Broader Market Today',
        date: 'Wed, September 30, 2026 at 9:15 PM UTC 4 min read',
        timestamp: '2026-09-30T21:15:03+00:00',
        preview: 'Waste Management (WM) shares declined more than the broader market today, driven by concerns over rising operational costs and potential regulatory ch...',
        stockSymbol: 'WM'},
    {id: 'ares-management-corporation-schedules-earnings-rel',
        emoji: '📰',
        title: 'Ares Management Corporation Schedules Earnings Release and Conference Call for the Third Quarter Ending September 30, 2026',
        date: 'Tue, September 29, 2026 at 10:00 PM UTC 2 min read',
        timestamp: '2026-09-29T22:00:00+00:00',
        preview: 'Ares Management Corporation has announced the scheduling of its earnings release and conference call for the third quarter ending September 30, 2026. ...',
        stockSymbol: 'ARES'},
    {id: 'illinois-tool-works-itw-following-zacks-upgrade-ha',
        emoji: '📰',
        title: 'Illinois Tool Works (ITW) Following Zacks Upgrade Has Valuation Back In Focus',
        date: 'Wed, September 30, 2026 at 1:11 PM UTC 3 min read',
        timestamp: '2026-09-30T13:11:51+00:00',
        preview: 'Illinois Tool Works (ITW) received an upgrade from Zacks Investment Research, prompting renewed attention on its valuation metrics. This upgrade could...',
        stockSymbol: 'ITW'},
    {id: 'should-investors-buy-byd-s-stock-in-october',
        emoji: '📰',
        title: 'Should Investors Buy BYD\'s Stock in October?',
        date: 'Tue, September 29, 2026 at 7:27 PM UTC 3 min read',
        timestamp: '2026-09-29T19:27:00+00:00',
        preview: 'In October, analysts are evaluating whether investors should consider buying BYD\'s stock amid its recent performance and market trends. The company\'s ...',
        stockSymbol: '1211.HK'},
    {id: 'brixmor-property-slate-acquisition-seen-as-rock-so',
        emoji: '📰',
        title: 'Brixmor Property Slate Acquisition Seen as \'Rock Solid\' Investment, UBS Says',
        date: 'Tue, September 29, 2026 at 5:03 PM UTC 4 min read',
        timestamp: '2026-09-29T17:03:36+00:00',
        preview: 'UBS has labeled Brixmor Property Group\'s recent slate acquisition as a "rock solid" investment, highlighting its potential for strong returns. This en...',
        stockSymbol: 'BRX'},
    {id: 'why-preferred-bank-pfbc-is-a-great-dividend-stock',
        emoji: '📰',
        title: 'Why Preferred Bank (PFBC) is a Great Dividend Stock Right Now',
        date: 'Wed, September 30, 2026 at 2:45 PM UTC 3 min read',
        timestamp: '2026-09-30T14:45:02+00:00',
        preview: 'Preferred Bank (PFBC) has been highlighted as an attractive dividend stock due to its consistent dividend payments and strong financial performance. T...',
        stockSymbol: 'PFBC'},
    {id: 'what-to-expect-from-texas-instruments-q3-2026-earn',
        emoji: '📰',
        title: 'What to Expect From Texas Instruments’ Q3 2026 Earnings Report',
        date: 'Wed, September 30, 2026 at 1:47 PM UTC 4 min read',
        timestamp: '2026-09-30T13:47:15+00:00',
        preview: 'Texas Instruments is set to release its Q3 2026 earnings report, with analysts anticipating a moderate revenue growth driven by strong demand in the a...',
        stockSymbol: 'TXN'},
    {id: 'amp-s-5-5b-buyback-aids-shareholder-returns-will-i',
        emoji: '📰',
        title: 'AMP\'s $5.5B Buyback Aids Shareholder Returns: Will It Be Sustainable?',
        date: 'Wed, September 30, 2026 at 1:27 PM UTC 4 min read',
        timestamp: '2026-09-30T13:27:00+00:00',
        preview: 'AMP announced a $5.5 billion share buyback program aimed at enhancing shareholder returns. This initiative is significant as it reflects the company\'s...',
        stockSymbol: 'AMP'},
    {id: 'eaton-trades-at-a-premium-to-industry-what-investo',
        emoji: '📰',
        title: 'Eaton Trades at a Premium to Industry: What Investors Should Know',
        date: 'Wed, September 30, 2026 at 4:24 PM UTC 4 min read',
        timestamp: '2026-09-30T16:24:00+00:00',
        preview: 'Eaton Corporation is currently trading at a premium compared to its industry peers, raising questions about its valuation. This premium may reflect in...',
        stockSymbol: 'ETN'},
    {id: 'rum-stock-ticks-higher-overnight-analyst-sees-94-u',
        emoji: '📰',
        title: 'RUM Stock Ticks Higher Overnight: Analyst Sees 94% Upside As $13B Anthropic Deal Sets Off AI Pivot',
        date: 'Wed, September 30, 2026 at 1:37 AM UTC 4 min read',
        timestamp: '2026-09-30T01:37:50+00:00',
        preview: 'RUM stock experienced a slight increase overnight following an analyst\'s projection of a 94% upside potential, driven by a significant $13 billion dea...',
        stockSymbol: 'RUM'},
    {id: 'amazon-signs-1-billion-synopsys-deal-as-aws-steps',
        emoji: '📰',
        title: 'Amazon Signs $1 Billion Synopsys Deal as AWS Steps Up Nvidia Challenge',
        date: 'Wed, September 30, 2026 at 7:33 PM UTC 3 min read',
        timestamp: '2026-09-30T19:33:19+00:00',
        preview: 'Amazon has signed a significant $1 billion deal with Synopsys, aimed at enhancing its AWS offerings and intensifying competition against Nvidia in the...',
        stockSymbol: 'SNPS'},
    {id: 'fortem-technologies-closes-50m-series-b-financing',
        emoji: '📰',
        title: 'Fortem Technologies Closes $50M Series B Financing Led by Lockheed Martin',
        date: 'Wed, September 30, 2026 at 2:30 PM UTC 2 min read',
        timestamp: '2026-09-30T14:30:00+00:00',
        preview: 'Fortem Technologies has successfully closed a $50 million Series B financing round, with Lockheed Martin leading the investment. This partnership enha...',
        stockSymbol: 'LMT'},
    {id: 'mgni-stock-heads-for-another-month-in-green-magnit',
        emoji: '📰',
        title: 'MGNI Stock Heads For Another Month In Green: Magnite Gets Price Target Boost As Google Ad-Tech Changes Open New Growth Path',
        date: 'Wed, September 30, 2026 at 9:06 AM UTC 4 min read',
        timestamp: '2026-09-30T09:06:07+00:00',
        preview: 'MGNI stock is poised for another month of gains following an increase in its price target, driven by recent changes in Google\'s advertising technology...',
        stockSymbol: 'MGNI'},
    {id: 'q2-earnings-roundup-lovesac-nasdaq-love-and-the-re',
        emoji: '📰',
        title: 'Q2 Earnings Roundup: Lovesac (NASDAQ:LOVE) And The Rest Of The Consumer Discretionary - Home Furnishings Segment',
        date: 'Tue, September 29, 2026 at 7:28 PM UTC 4 min read',
        timestamp: '2026-09-29T19:28:02+00:00',
        preview: 'Lovesac (NASDAQ: LOVE) reported its Q2 earnings, showcasing strong performance within the consumer discretionary home furnishings segment. The company...',
        stockSymbol: 'LOVE'},
    {id: 'a-look-back-at-consumer-discretionary-travel-and-v',
        emoji: '📰',
        title: 'A Look Back at Consumer Discretionary - Travel and Vacation Providers Stocks’ Q2 Earnings: Marriott Vacations (NYSE:VAC) Vs The Rest Of The Pack',
        date: 'Tue, September 29, 2026 at 8:08 PM UTC 4 min read',
        timestamp: '2026-09-29T20:08:02+00:00',
        preview: 'Marriott Vacations (NYSE: VAC) reported its Q2 earnings, showcasing resilience amid a competitive consumer discretionary sector, particularly among tr...',
        stockSymbol: 'VAC'},
    {id: 'desktop-virtualization-market-report-2026-capitali',
        emoji: '📰',
        title: 'Desktop Virtualization Market Report 2026: Capitalize on the $29.51 Billion Market by 2030 as DaaS, Zero Trust and Hybrid Work Disrupt IT — Benchmark Citrix, VMware, Microsoft, AWS and Nutanix to Secure Share at 13% CAGR',
        date: 'Tue, September 29, 2026 at 3:53 PM UTC 3 min read',
        timestamp: '2026-09-29T15:53:00+00:00',
        preview: 'A recent report projects the desktop virtualization market to reach $29.51 billion by 2030, with a compound annual growth rate (CAGR) of 13%. This gro...',
        stockSymbol: 'NTNX'},
    {id: 'what-you-need-to-know-ahead-of-regions-financial-s',
        emoji: '📰',
        title: 'What You Need to Know Ahead of Regions Financial\'s Earnings Release',
        date: 'Wed, September 30, 2026 at 12:52 PM UTC 3 min read',
        timestamp: '2026-09-30T12:52:57+00:00',
        preview: 'Regions Financial is set to release its earnings report soon, which is highly anticipated by investors. Analysts are particularly focused on the bank\'...',
        stockSymbol: 'RF'},
    {id: 'amkor-technology-amkr-advances-while-market-declin',
        emoji: '📰',
        title: 'Amkor Technology (AMKR) Advances While Market Declines: Some Information for Investors',
        date: 'Tue, September 29, 2026 at 8:50 PM UTC 2 min read',
        timestamp: '2026-09-29T20:50:02+00:00',
        preview: 'Amkor Technology (AMKR) has seen a notable increase in its stock price despite a general market decline. This resilience may indicate strong investor ...',
        stockSymbol: 'AMKR'},
    {id: 'powerfleet-unity-recognized-for-end-to-end-aiot-in',
        emoji: '📰',
        title: 'Powerfleet Unity Recognized for End-to-End AIoT Innovation Across Enterprise Operations',
        date: 'Wed, September 30, 2026 at 12:00 PM UTC 3 min read',
        timestamp: '2026-09-30T12:00:00+00:00',
        preview: 'Powerfleet Unity has been recognized for its innovative end-to-end AIoT solutions that enhance enterprise operations. This acknowledgment highlights t...',
        stockSymbol: 'AIOT'},
    {id: 'barclays-secures-fca-nod-to-provide-targeted-inves',
        emoji: '📰',
        title: 'Barclays secures FCA nod to provide targeted investor support',
        date: 'Wed, September 30, 2026 at 11:53 AM UTC 3 min read',
        timestamp: '2026-09-30T11:53:36+00:00',
        preview: 'Barclays (BARC.L) has received approval from the Financial Conduct Authority (FCA) to offer targeted support to investors. This development is signifi...',
        stockSymbol: 'BARC.L'},
    {id: 'hci-group-hci-falls-more-steeply-than-broader-mark',
        emoji: '📰',
        title: 'HCI Group (HCI) Falls More Steeply Than Broader Market: What Investors Need to Know',
        date: 'Wed, September 30, 2026 at 9:00 PM UTC 4 min read',
        timestamp: '2026-09-30T21:00:04+00:00',
        preview: 'HCI Group (HCI) experienced a significant decline, falling more steeply than the broader market. This drop raises concerns for investors, as it may in...',
        stockSymbol: 'HCI'},
    {id: 'bank-of-america-to-convene-500-innovators-and-capi',
        emoji: '📰',
        title: 'Bank of America to Convene 500+ Innovators and Capital Providers at 15th Annual Technology Innovation Summit',
        date: 'Wed, September 30, 2026 at 2:00 PM UTC 4 min read',
        timestamp: '2026-09-30T14:00:00+00:00',
        preview: 'Bank of America is set to host its 15th Annual Technology Innovation Summit, bringing together over 500 innovators and capital providers. This event h...',
        stockSymbol: 'BAC'},
    {id: 'pegasystems-pega-is-down-51-and-just-got-downgrade',
        emoji: '📰',
        title: 'Pegasystems (PEGA) Is Down 51% and Just Got Downgraded on AI Fears. Victim or Bargain?',
        date: 'Wed, September 30, 2026 at 5:15 AM UTC 3 min read',
        timestamp: '2026-09-30T05:15:59+00:00',
        preview: 'Pegasystems (PEGA) shares have plummeted 51% following a downgrade amid concerns over its competitiveness in the AI sector. This significant decline r...',
        stockSymbol: 'PEGA'},
    {id: 'is-ai-driven-edge-security-integration-with-nvidia',
        emoji: '📰',
        title: 'Is AI-Driven Edge Security Integration With Nvidia’s Stack Altering The Investment Case For Palo Alto Networks (PANW)?',
        date: 'Thu, October 1, 2026 at 1:23 AM UTC 3 min read',
        timestamp: '2026-10-01T01:23:37+00:00',
        preview: 'Palo Alto Networks (PANW) is integrating its AI-driven edge security solutions with Nvidia\'s technology, potentially enhancing its cybersecurity offer...',
        stockSymbol: 'PANW'},
    {id: 'haemonetics-sets-date-for-publishing-second-quarte',
        emoji: '📰',
        title: 'Haemonetics Sets Date for Publishing Second Quarter Fiscal Year 2027 Results: November 5, 2026',
        date: 'Wed, September 30, 2026 at 8:05 PM UTC 4 min read',
        timestamp: '2026-09-30T20:05:00+00:00',
        preview: 'Haemonetics Corporation (HAE) has announced that it will release its second quarter fiscal year 2027 financial results on November 5, 2026. This upcom...',
        stockSymbol: 'HAE'},
    {id: 'redwire-joins-growing-orbital-data-center-race-wit',
        emoji: '📰',
        title: 'Redwire Joins Growing Orbital Data Center Race With Sophia Days After $980M Space Force Contract Selection',
        date: 'Wed, September 30, 2026 at 10:59 AM UTC 3 min read',
        timestamp: '2026-09-30T10:59:04+00:00',
        preview: 'Redwire has entered the competitive orbital data center market with the launch of its new initiative, Sophia, shortly after securing a significant $98...',
        stockSymbol: 'RDW'},
    {id: 'louisiana-pacific-lpx-sees-a-more-significant-dip',
        emoji: '📰',
        title: 'Louisiana-Pacific (LPX) Sees a More Significant Dip Than Broader Market: Some Facts to Know',
        date: 'Wed, September 30, 2026 at 9:00 PM UTC 4 min read',
        timestamp: '2026-09-30T21:00:05+00:00',
        preview: 'Louisiana-Pacific (LPX) experienced a more substantial decline in its stock price compared to the broader market, reflecting investor concerns over sl...',
        stockSymbol: 'LPX'},
    {id: 'should-value-investors-buy-gray-media-inc-gtn-stoc',
        emoji: '📰',
        title: 'Should Value Investors Buy Gray Media Inc. (GTN) Stock?',
        date: 'Wed, September 30, 2026 at 12:40 PM UTC 2 min read',
        timestamp: '2026-09-30T12:40:03+00:00',
        preview: 'Gray Media Inc. (GTN) is currently being evaluated by value investors as potential buying opportunities arise amid recent market fluctuations. Analyst...',
        stockSymbol: 'GTN'},
    {id: 'nvent-electric-nvt-stock-looks-stretched-against-c',
        emoji: '📰',
        title: 'nVent Electric (NVT) Stock Looks Stretched Against Current Earnings Power',
        date: 'Wed, September 30, 2026 at 9:06 AM UTC 2 min read',
        timestamp: '2026-09-30T09:06:52+00:00',
        preview: 'nVent Electric (NVT) stock has been identified as potentially overvalued based on its current earnings power, suggesting that its price may not be jus...',
        stockSymbol: 'NVT'},
    {id: 'urbn-vs-zgn-which-stock-should-value-investors-buy',
        emoji: '📰',
        title: 'URBN vs. ZGN: Which Stock Should Value Investors Buy Now?',
        date: 'Tue, September 29, 2026 at 2:40 PM UTC 4 min read',
        timestamp: '2026-09-29T14:40:04+00:00',
        preview: 'In a recent analysis comparing URBN and ZGN, analysts highlighted ZGN\'s strong fundamentals and growth potential, positioning it as a favorable option...',
        stockSymbol: 'ZGN'},
    {id: 'rio-tinto-tasmanian-government-and-commonwealth-go',
        emoji: '📰',
        title: 'Rio Tinto, Tasmanian Government and Commonwealth Government secure the future of Bell Bay Aluminium until 2031',
        date: 'Wed, September 30, 2026 at 9:00 PM UTC 4 min read',
        timestamp: '2026-09-30T21:00:00+00:00',
        preview: 'Rio Tinto, in collaboration with the Tasmanian and Commonwealth Governments, has secured the future of Bell Bay Aluminium through a new agreement that...',
        stockSymbol: 'RIO.AX'},
    {id: 'dental-equipment-technology-stocks-q2-earnings-rev',
        emoji: '📰',
        title: 'Dental Equipment & Technology Stocks Q2 Earnings Review: Envista (NYSE:NVST) Shines',
        date: 'Wed, September 30, 2026 at 7:57 PM UTC 4 min read',
        timestamp: '2026-09-30T19:57:13+00:00',
        preview: 'Envista Holdings Corporation (NYSE: NVST) reported strong Q2 earnings, outperforming analyst expectations and demonstrating robust growth in its denta...',
        stockSymbol: 'NVST'},
    {id: 'asml-tsm-earnings-could-expose-a-new-risk-for-the',
        emoji: '📰',
        title: 'ASML, TSM Earnings Could Expose a New Risk for the AI Trade',
        date: 'Wed, September 30, 2026 at 12:05 PM UTC 2 min read',
        timestamp: '2026-09-30T12:05:40+00:00',
        preview: 'ASML and TSMC\'s recent earnings reports may reveal potential vulnerabilities in the AI sector, raising concerns for investors heavily invested in AI-r...',
        stockSymbol: 'ASML'},
    {id: 'is-exxonmobil-holdings-xom-fully-valued-following',
        emoji: '📰',
        title: 'Is ExxonMobil Holdings (XOM) Fully Valued Following Vietnam Supply Deals And Texas Carbon Capture?',
        date: 'Wed, September 30, 2026 at 11:13 AM UTC 3 min read',
        timestamp: '2026-09-30T11:13:12+00:00',
        preview: 'ExxonMobil (XOM) recently secured supply deals in Vietnam and announced advancements in its Texas carbon capture initiatives. These developments are s...',
        stockSymbol: 'XOM'},
    {id: 'conagra-brands-q1-earnings-call-highlights',
        emoji: '📰',
        title: 'Conagra Brands Q1 Earnings Call Highlights',
        date: 'Wed, September 30, 2026 at 4:02 PM UTC 3 min read',
        timestamp: '2026-09-30T16:02:47+00:00',
        preview: 'Conagra Brands reported its Q1 earnings, showcasing a revenue increase driven by strong demand for its frozen and snack products. The company highligh...',
        stockSymbol: 'CAG'},
    {id: 'kimberly-clark-kmb-launches-exchange-offers-for-ou',
        emoji: '📰',
        title: 'Kimberly Clark (KMB) Launches Exchange Offers For Outstanding Notes',
        date: 'Wed, September 30, 2026 at 10:08 PM UTC 4 min read',
        timestamp: '2026-09-30T22:08:23+00:00',
        preview: 'Kimberly Clark (KMB) has initiated exchange offers for its outstanding notes, allowing investors to swap their current debt securities for new ones. T...',
        stockSymbol: 'KMB'},
    {id: 'morgan-stanley-sees-buying-opportunity-in-beaten-d',
        emoji: '📰',
        title: 'Morgan Stanley sees buying opportunity in beaten-down Boeing stock',
        date: 'Thu, October 1, 2026 at 12:37 AM UTC 3 min read',
        timestamp: '2026-10-01T00:37:00+00:00',
        preview: 'Morgan Stanley has identified a buying opportunity in Boeing\'s stock, which has recently experienced a significant decline. The firm believes that the...',
        stockSymbol: 'MS'},
    {id: 'larimar-therapeutics-strengthens-executive-leaders',
        emoji: '📰',
        title: 'Larimar Therapeutics Strengthens Executive Leadership with Appointment of John Harlow as President and Chief Operating Officer',
        date: 'Tue, September 29, 2026 at 8:05 PM UTC 2 min read',
        timestamp: '2026-09-29T20:05:00+00:00',
        preview: 'Larimar Therapeutics has appointed John Harlow as President and Chief Operating Officer, enhancing its executive leadership team. This strategic move ...',
        stockSymbol: 'LRMR'},
    {id: 'ingram-micro-ingm-upgraded-to-buy-here-s-why',
        emoji: '📰',
        title: 'Ingram Micro (INGM) Upgraded to Buy: Here\'s Why',
        date: 'Wed, September 30, 2026 at 3:00 PM UTC 4 min read',
        timestamp: '2026-09-30T15:00:03+00:00',
        preview: 'Ingram Micro (INGM) has been upgraded to a "Buy" rating by analysts, reflecting a positive outlook on the company\'s growth potential and market positi...',
        stockSymbol: 'INGM'},
    {id: 'cigna-ci-stock-looks-reasonable-against-its-earnin',
        emoji: '📰',
        title: 'Cigna (CI) Stock Looks Reasonable Against Its Earnings Power',
        date: 'Wed, September 30, 2026 at 4:18 PM UTC 4 min read',
        timestamp: '2026-09-30T16:18:11+00:00',
        preview: 'Cigna (CI) stock has been assessed as reasonably valued based on its earnings potential, indicating that the current price may not fully reflect the c...',
        stockSymbol: 'CI'},
    {id: 'bill-and-blackbaud-partner-to-simplify-vendor-paym',
        emoji: '📰',
        title: 'BILL and Blackbaud Partner to Simplify Vendor Payments for Nonprofit and Education Finance Teams',
        date: 'Tue, September 29, 2026 at 1:45 PM UTC 4 min read',
        timestamp: '2026-09-29T13:45:00+00:00',
        preview: 'BILL has announced a partnership with Blackbaud to streamline vendor payments specifically for nonprofit and education finance teams. This collaborati...',
        stockSymbol: 'BILL'},
    {id: 'ceg-stock-rises-overnight-constellation-signs-20-y',
        emoji: '📰',
        title: 'CEG Stock Rises Overnight: Constellation Signs 20-Year Nuclear Power Deal With Amazon',
        date: 'Thu, October 1, 2026 at 1:16 AM UTC 2 min read',
        timestamp: '2026-10-01T01:16:26+00:00',
        preview: 'CEG stock experienced an overnight increase following Constellation\'s announcement of a 20-year nuclear power agreement with Amazon. This deal is sign...',
        stockSymbol: 'CEG'},
    {id: 'hpe-cfo-discusses-1-2b-deal-with-vultr-to-deploy-a',
        emoji: '📰',
        title: 'HPE CFO discusses $1.2B deal with Vultr to deploy AMD Helios AI racks',
        date: 'Wed, September 30, 2026 at 7:42 PM UTC 4 min read',
        timestamp: '2026-09-30T19:42:17+00:00',
        preview: 'Hewlett Packard Enterprise (HPE) announced a $1.2 billion deal with Vultr to deploy AMD Helios AI racks, marking a significant partnership in the grow...',
        stockSymbol: 'AMD'},
    {id: 'ntap-stock-hits-record-high-netapp-expands-strateg',
        emoji: '📰',
        title: 'NTAP Stock Hits Record High: NetApp Expands Strategic Partnerships With SAP, Oracle, and Supermicro To Drive Cloud Infrastructure',
        date: 'Tue, September 29, 2026 at 7:47 PM UTC 2 min read',
        timestamp: '2026-09-29T19:47:48+00:00',
        preview: 'NTAP stock reached a record high following the company\'s announcement of expanded strategic partnerships with SAP, Oracle, and Supermicro, aimed at en...',
        stockSymbol: 'NTAP'},
    {id: 'mckesson-mck-sees-a-more-significant-dip-than-broa',
        emoji: '📰',
        title: 'McKesson (MCK) Sees a More Significant Dip Than Broader Market: Some Facts to Know',
        date: 'Wed, September 30, 2026 at 9:00 PM UTC 3 min read',
        timestamp: '2026-09-30T21:00:04+00:00',
        preview: 'McKesson (MCK) experienced a notable decline in its stock price, surpassing the broader market\'s downturn. This dip raises concerns for investors, as ...',
        stockSymbol: 'MCK'},
    {id: 'roku-stock-is-up-40-in-2026-here-s-what-backs-it-i',
        emoji: '📰',
        title: 'Roku Stock Is Up 40% in 2026. Here’s What Backs It If the Fox Deal Breaks',
        date: 'Wed, September 30, 2026 at 12:38 PM UTC 2 min read',
        timestamp: '2026-09-30T12:38:41+00:00',
        preview: 'Roku\'s stock has surged 40% in 2026, driven by speculation surrounding a potential deal with Fox that could significantly enhance its content offering...',
        stockSymbol: 'FOXA'},
    {id: 'how-pepsico-uses-chefs-to-think-differently-about',
        emoji: '📰',
        title: 'How PepsiCo uses chefs to think differently about innovation',
        date: 'Wed, September 30, 2026 at 3:00 PM UTC 3 min read',
        timestamp: '2026-09-30T15:00:00+00:00',
        preview: 'PepsiCo has engaged chefs to drive innovative product development, aiming to enhance its portfolio with unique flavors and culinary insights. This str...',
        stockSymbol: 'PEP'},
    {id: 'blackberry-s-alloy-kore-scores-big-can-it-unlock-h',
        emoji: '📰',
        title: 'BlackBerry\'s Alloy Kore Scores Big: Can It Unlock Higher QNX Revenue?',
        date: 'Wed, September 30, 2026 at 1:34 PM UTC 3 min read',
        timestamp: '2026-09-30T13:34:00+00:00',
        preview: 'BlackBerry\'s Alloy Kore has achieved significant success, potentially unlocking higher revenue for its QNX software segment. This development is cruci...',
        stockSymbol: 'BB.TO'},
    {id: 'roblox-stock-is-down-70-from-its-high-after-a-jeff',
        emoji: '📰',
        title: 'Roblox Stock Is Down 70% From Its High After a Jefferies Downgrade and a Child Safety Lawsuit Ruling',
        date: 'Wed, September 30, 2026 at 6:12 PM UTC 2 min read',
        timestamp: '2026-09-30T18:12:33+00:00',
        preview: 'Roblox Corporation\'s stock has plummeted 70% from its peak following a downgrade by Jefferies and a recent court ruling concerning a child safety laws...',
        stockSymbol: 'RBLX'},
    {id: 'cboe-cboe-surges-3-4-is-this-an-indication-of-furt',
        emoji: '📰',
        title: 'CBOE (CBOE) Surges 3.4%: Is This an Indication of Further Gains?',
        date: 'Wed, September 30, 2026 at 1:44 PM UTC 4 min read',
        timestamp: '2026-09-30T13:44:00+00:00',
        preview: 'CBOE Holdings (CBOE) experienced a notable surge of 3.4%, raising investor interest in potential further gains. This uptick may indicate positive mark...',
        stockSymbol: 'CBOE'},
    {id: 'can-fee-based-businesses-lift-equitable-holdings-e',
        emoji: '📰',
        title: 'Can Fee-Based Businesses Lift Equitable Holdings\' Earnings Mix?',
        date: 'Wed, September 30, 2026 at 4:07 PM UTC 3 min read',
        timestamp: '2026-09-30T16:07:00+00:00',
        preview: 'Equitable Holdings (EQH) is exploring the potential of fee-based businesses to enhance its earnings mix, aiming to diversify revenue streams beyond tr...',
        stockSymbol: 'EQH'},
    {id: 'cbl-properties-closes-two-strategic-land-sales-bri',
        emoji: '📰',
        title: 'CBL Properties Closes Two Strategic Land Sales, Bringing Year-to-Date Land Sale Proceeds to More Than $30 Million',
        date: 'Wed, September 30, 2026 at 8:29 PM UTC 3 min read',
        timestamp: '2026-09-30T20:29:00+00:00',
        preview: 'CBL Properties has successfully closed two strategic land sales, increasing its year-to-date land sale proceeds to over $30 million. This move is sign...',
        stockSymbol: 'CBL'},
    {id: 'is-it-worth-investing-in-disney-dis-based-on-wall',
        emoji: '📰',
        title: 'Is It Worth Investing in Disney (DIS) Based on Wall Street\'s Bullish Views?',
        date: 'Wed, September 30, 2026 at 12:30 PM UTC 4 min read',
        timestamp: '2026-09-30T12:30:02+00:00',
        preview: 'Disney (DIS) has garnered positive attention from Wall Street analysts, with several issuing bullish ratings amid expectations of a strong recovery in...',
        stockSymbol: 'DIS'},
    {id: 'fed-s-cook-inflation-has-been-too-high-for-too-lon',
        emoji: '📊',
        title: 'Fed\'s Cook: inflation has been too high for too long - reuters.com',
        date: 'Wed, September 30, 2026 at 7:28 PM UTC 3 min read',
        timestamp: '2026-09-30T19:28:23+00:00',
        preview: 'In a recent statement, Federal Reserve Governor Lisa Cook emphasized that inflation has remained excessively high for an extended period, prompting co...',
        stockSymbol: '',
        link: ''},
    {id: 'neel-kashkari-q-a-at-the-council-on-foreign-relati',
        emoji: '📰',
        title: 'Neel Kashkari Q&A at the Council on Foreign Relations',
        date: 'Wed, September 30, 2026 at 10:00 PM UTC 3 min read',
        timestamp: '2026-09-30T22:00:00+00:00',
        preview: 'In a recent Q&A session at the Council on Foreign Relations, Neel Kashkari, President of the Federal Reserve Bank of Minneapolis, discussed the curren...',
        stockSymbol: '',
        link: ''},
    {id: 'albertsons-companies-announces-second-quarter-fisc',
        emoji: '📰',
        title: 'Albertsons Companies Announces Second Quarter Fiscal 2026 Earnings Release and Conference Call Date',
        date: 'Tue, September 29, 2026 at 8:05 PM UTC 3 min read',
        timestamp: '2026-09-29T20:05:53+00:00',
        preview: 'Albertsons Companies has announced the release date for its second quarter fiscal 2026 earnings report, scheduled for June 15, 2026. The company will ...',
        stockSymbol: '',
        link: ''},
    {id: 'federal-reserve-staffer-removed-sensitive-files-be',
        emoji: '📊',
        title: 'Federal Reserve Staffer Removed Sensitive Files Before Retiring, Report Finds',
        date: 'Mon, September 28, 2026 at 4:54 PM UTC 3 min read',
        timestamp: '2026-09-28T16:54:00+00:00',
        preview: 'A recent report from the Wall Street Journal reveals that a Federal Reserve staffer removed sensitive files prior to their retirement, raising concern...',
        stockSymbol: '',
        link: ''},
    {id: 'monetary-policy-overtakes-inflation-as-cfos-top-co',
        emoji: '📊',
        title: 'Monetary policy overtakes inflation as CFOs top concern',
        date: 'Mon, September 28, 2026 at 5:51 PM UTC 3 min read',
        timestamp: '2026-09-28T17:51:04+00:00',
        preview: 'In a recent survey, Chief Financial Officers (CFOs) have identified monetary policy as their primary concern, surpassing inflation for the first time ...',
        stockSymbol: '',
        link: ''},
    {id: 'key-us-data-this-week-seen-bolstering-case-for-oct',
        emoji: '📊',
        title: 'Key US Data This Week Seen Bolstering Case for October Rate Hike - Bloomberg.com',
        date: 'Mon, September 28, 2026 at 10:00 AM UTC 3 min read',
        timestamp: '2026-09-28T10:00:00+00:00',
        preview: 'This week, key U.S. economic data is anticipated to strengthen the argument for an interest rate hike by the Federal Reserve in October. Analysts are ...',
        stockSymbol: '',
        link: ''},
    {id: 'we-re-witnessing-the-stock-market-do-something-for',
        emoji: '📰',
        title: 'We\'re Witnessing the Stock Market Do Something for Only the 3rd Time in 156 Years, and History Is Crystal Clear About What\'s Next for Stocks',
        date: 'Sun, September 27, 2026 at 10:57 AM UTC 3 min read',
        timestamp: '2026-09-27T10:57:59+00:00',
        preview: 'The stock market is currently experiencing a rare phenomenon, occurring for only the third time in 156 years, which could have significant implication...',
        stockSymbol: '',
        link: ''},
    {id: 'prediction-a-stock-market-crash-is-coming-heres-th',
        emoji: '🔴',
        title: 'Prediction: A Stock Market Crash Is Coming. Heres the One Move You Should Make, According to History.',
        date: 'Sun, September 27, 2026 at 12:05 PM UTC 3 min read',
        timestamp: '2026-09-27T12:05:00+00:00',
        preview: 'A recent article from The Motley Fool warns that a stock market crash may be on the horizon, drawing on historical trends to support this prediction. ...',
        stockSymbol: '',
        link: ''},
    {id: 'silgan-to-release-third-quarter-2026-earnings-resu',
        emoji: '📰',
        title: 'Silgan to Release Third Quarter 2026 Earnings Results on October 29, 2026',
        date: 'Fri, September 25, 2026 at 9:20 PM UTC 3 min read',
        timestamp: '2026-09-25T21:20:00+00:00',
        preview: 'Silgan Holdings Inc. has announced that it will release its third quarter 2026 earnings results on October 29, 2026. Investors will be keenly watching...',
        stockSymbol: '',
        link: ''},
    {id: 'reducing-environmental-hazards-in-k12-schools-can',
        emoji: '📰',
        title: 'Reducing Environmental Hazards In K12 Schools Can Boost Students Lifetime Earnings - urban.org',
        date: 'Fri, September 25, 2026 at 12:00 PM UTC 3 min read',
        timestamp: '2026-09-25T12:00:00+00:00',
        preview: 'A recent study by Urban Institute highlights that reducing environmental hazards in K-12 schools can significantly enhance students\' lifetime earnings...',
        stockSymbol: '',
        link: ''},
    {id: 'micron-technology-stock-wavers-ahead-of-fiscal-q4',
        emoji: '📰',
        title: 'Micron Technology Stock Wavers Ahead Of Fiscal Q4 Earnings Report - Investor\'s Business Daily',
        date: 'Fri, September 25, 2026 at 8:20 PM UTC 3 min read',
        timestamp: '2026-09-25T20:20:00+00:00',
        preview: 'Micron Technology\'s stock has shown volatility as investors await its fiscal Q4 earnings report, scheduled for release on September 28. The semiconduc...',
        stockSymbol: '',
        link: ''},
    {id: 'fed-s-williams-says-it-is-reasonable-to-see-anothe',
        emoji: '📊',
        title: 'Fed\'s Williams says it is reasonable to see another US rate hike this year',
        date: 'Thu, September 24, 2026 at 2:17 PM UTC 3 min read',
        timestamp: '2026-09-24T14:17:57+00:00',
        preview: 'In a recent statement, Federal Reserve Bank of New York President John Williams indicated that it is reasonable to anticipate another interest rate hi...',
        stockSymbol: '',
        link: ''},
    {id: 'rising-treasury-yields-could-push-car-loan-rates-h',
        emoji: '📊',
        title: 'Rising Treasury yields could push car loan rates higher, experts say. What buyers need to know',
        date: 'Thu, September 24, 2026 at 4:14 PM UTC 3 min read',
        timestamp: '2026-09-24T16:14:35+00:00',
        preview: 'Rising Treasury yields are expected to lead to higher car loan rates, according to financial experts. As the yield on the 10-year Treasury note has re...',
        stockSymbol: '',
        link: ''},
    {id: 'commentary-passive-investing-that-s-p-500-index-fu',
        emoji: '📰',
        title: 'COMMENTARY: Passive investing? That S&P 500 index fund is basically a tech fund',
        date: 'Wed, September 23, 2026 at 11:40 PM UTC 3 min read',
        timestamp: '2026-09-23T23:40:35+00:00',
        preview: 'The S&P 500 index, often viewed as a benchmark for passive investing, has increasingly become dominated by technology stocks. As of recent data, tech ...',
        stockSymbol: '',
        link: ''},
    {id: 'dow-jones-futures-fall-after-nasdaq-hits-new-high',
        emoji: '🔴',
        title: 'Dow Jones Futures Fall After Nasdaq Hits New High; Sandisk, Micron Trigger Buy Signals - Investor\'s Business Daily',
        date: 'Wed, September 23, 2026 at 12:05 PM UTC 3 min read',
        timestamp: '2026-09-23T12:05:00+00:00',
        preview: 'Dow Jones futures experienced a decline following the Nasdaq\'s recent surge to a new record high, reflecting a mixed sentiment in the market. Notably,...',
        stockSymbol: '',
        link: ''},
    {id: '5-things-to-know-before-the-stock-market-opens-on',
        emoji: '📰',
        title: '5 Things to Know Before the Stock Market Opens on Wednesday',
        date: 'Wed, September 23, 2026 at 12:18 PM UTC 3 min read',
        timestamp: '2026-09-23T12:18:54+00:00',
        preview: 'As the stock market prepares to open on Wednesday, investors should be aware of several key developments. Notably, major indices are poised for a mixe...',
        stockSymbol: '',
        link: ''},
    {id: 'anthropic-ipo-what-10b5-1-plans-mean-for-employees',
        emoji: '📰',
        title: 'Anthropic IPO: What 10b5-1 Plans Mean For Employees',
        date: 'Tue, September 22, 2026 at 8:28 PM UTC 3 min read',
        timestamp: '2026-09-22T20:28:18+00:00',
        preview: 'Anthropic, an AI research company, is preparing for its initial public offering (IPO) and has implemented 10b5-1 plans to facilitate stock sales for e...',
        stockSymbol: '',
        link: ''},
    {id: 'anthropics-ipo-will-happen-a-month-later-than-expe',
        emoji: '📰',
        title: 'Anthropics IPO Will Happen a Month Later Than Expected',
        date: 'Tue, September 22, 2026 at 6:45 PM UTC 3 min read',
        timestamp: '2026-09-22T18:45:29+00:00',
        preview: 'Anthropic, the artificial intelligence startup, has announced that its initial public offering (IPO) will be delayed by one month, now scheduled for l...',
        stockSymbol: '',
        link: ''},
    {id: 'northpointe-bancshares-inc-announces-date-of-third',
        emoji: '📰',
        title: 'Northpointe Bancshares, Inc. Announces Date of Third Quarter 2026 Earnings Release and Conference Call',
        date: 'Mon, September 21, 2026 at 8:27 PM UTC 3 min read',
        timestamp: '2026-09-21T20:27:00+00:00',
        preview: 'Northpointe Bancshares, Inc. has announced that it will release its earnings for the third quarter of 2026 on November 3, 2026. The company will also ...',
        stockSymbol: '',
        link: ''},
    {id: 'when-will-pharming-group-reveal-its-2024-financial',
        emoji: '🚀',
        title: 'When Will Pharming Group Reveal Its 2024 Financial Performance? Key Date Announced',
        date: 'Mon, September 21, 2026 at 8:54 PM UTC 3 min read',
        timestamp: '2026-09-21T20:54:01+00:00',
        preview: 'Pharming Group has announced that it will disclose its financial performance for the year 2024 on March 12, 2025. This announcement is significant for...',
        stockSymbol: '',
        link: ''}
];

// Render news items into the sidebar
function renderNewsItems() {
    const container = document.getElementById('news-items');
    if (!container) return;
    
    // Sort all items by date (newest first)
    const sortedItems = [...newsItems].sort((a, b) => {
        const dateA = new Date(a.date);
        const dateB = new Date(b.date);
        return dateB - dateA;
    });
    
    // Separate stock news and general news from sorted items
    const stockNews = sortedItems.filter(item => item.stockSymbol);
    const generalNews = sortedItems.filter(item => !item.stockSymbol);
    
    // Show 1 general + 4 stock news
    const displayItems = [];
    if (generalNews.length > 0) displayItems.push(generalNews[0]);
    displayItems.push(...stockNews.slice(0, 4));
    
    container.innerHTML = displayItems.map(item => {
        const url = item.stockSymbol ? `stocks/${item.stockSymbol}.html` : `news.html#${item.id}`;
        return `
        <div class="news-item" style="padding: 8px; margin-bottom: 8px; border-bottom: 1px solid var(--border-color); cursor: pointer;" onclick="window.location.href='${url}'">
            <div style="font-weight: 600; color: var(--text-primary); font-size: 0.85rem; margin-bottom: 3px;">${item.emoji} ${item.title}</div>
            <div style="color: var(--text-secondary); font-size: 0.7rem; margin-bottom: 2px;" data-timestamp="${item.timestamp || ''}" class="article-date">${item.date}</div>
            <div style="color: var(--text-secondary); font-size: 0.75rem; line-height: 1.3;">${item.preview}</div>
        </div>
        `;
    }).join('');
}

if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', renderNewsItems);
} else {
    renderNewsItems();
}
