// Shared news items for Market News sidebar
const newsItems = [
    {
        id: 'bluelinx-expands-lp-smartside-trim-siding-offering',
        emoji: '📰',
        title: 'BlueLinx Expands LP® SmartSide® Trim & Siding Offering Across Key U.S. Markets',
        date: 'Tue, September 29, 2026 at 1:15 PM UTC 2 min read',
        timestamp: '2026-09-29T13:15:00+00:00',
        preview: 'BlueLinx Holdings Inc. has announced the expansion of its LP® SmartSide® trim and siding product line into key U.S. markets. This strategic move is ai...',
        stockSymbol: 'BXC'
    },
    {
        id: 'peabody-energy-btu-buy-sell-or-hold-post-q2-earnin',
        emoji: '📰',
        title: 'Peabody Energy (BTU): Buy, Sell, or Hold Post Q2 Earnings?',
        date: 'Mon, September 28, 2026 at 5:26 PM UTC 2 min read',
        timestamp: '2026-09-28T17:26:36+00:00',
        preview: 'Peabody Energy (BTU) reported its Q2 earnings, prompting analysts to reassess their ratings on the stock. The results showed a mixed performance, with...',
        stockSymbol: 'BTU'
    },
    {
        id: 'kirby-corporation-announces-date-for-2026-third-qu',
        emoji: '📰',
        title: 'Kirby Corporation Announces Date for 2026 Third Quarter Earnings Release and Earnings Webcast',
        date: 'Mon, September 28, 2026 at 9:00 PM UTC 4 min read',
        timestamp: '2026-09-28T21:00:00+00:00',
        preview: 'Kirby Corporation has announced the date for its 2026 third quarter earnings release and accompanying earnings webcast. This event is significant for ...',
        stockSymbol: 'KEX'
    },
    {
        id: 'unpacking-q2-earnings-renasant-nyse-rnst-in-the-co',
        emoji: '📰',
        title: 'Unpacking Q2 Earnings: Renasant (NYSE:RNST) In The Context Of Other Regional Banks Stocks',
        date: 'Mon, September 28, 2026 at 8:38 PM UTC 3 min read',
        timestamp: '2026-09-28T20:38:36+00:00',
        preview: 'Renasant Corporation (NYSE: RNST) reported its Q2 earnings, showcasing a mixed performance compared to other regional bank stocks. While the bank expe...',
        stockSymbol: 'RNST'
    },
    {
        id: 'lineage-and-bsf-extend-25-year-relationship-based',
        emoji: '📰',
        title: 'Lineage and BSF Extend 25-Year Relationship Based on Trust and Innovation',
        date: 'Tue, September 29, 2026 at 6:10 PM UTC 3 min read',
        timestamp: '2026-09-29T18:10:00+00:00',
        preview: 'Lineage Logistics and BSF have renewed their partnership, extending their 25-year relationship, which is built on trust and innovation. This collabora...',
        stockSymbol: 'LINE'
    },
    {
        id: 'applied-digital-falls-6-despite-70-buy-initiation',
        emoji: '📰',
        title: 'Applied Digital Falls 6% Despite $70 Buy Initiation at Jones Trading; TeraWulf and Core Scientific Drop 4%',
        date: 'Mon, September 28, 2026 at 3:58 PM UTC 4 min read',
        timestamp: '2026-09-28T15:58:14+00:00',
        preview: 'Applied Digital\'s stock fell 6% following a $70 buy initiation from Jones Trading, indicating a disconnect between analyst optimism and market perform...',
        stockSymbol: 'WULF'
    },
    {
        id: 'crowdstrike-vs-uipath-what-revenue-patterns-tell-i',
        emoji: '📰',
        title: 'CrowdStrike vs. UiPath: What Revenue Patterns Tell Investors About These High-Growth Tech Companies',
        date: 'Tue, September 29, 2026 at 8:54 PM UTC 4 min read',
        timestamp: '2026-09-29T20:54:54+00:00',
        preview: 'Recent analysis comparing CrowdStrike and UiPath highlights differing revenue patterns that could influence investor decisions. While CrowdStrike has ...',
        stockSymbol: 'PATH'
    },
    {
        id: 'sumitomo-mitsui-financial-group-inc-s-dividend-ana',
        emoji: '📰',
        title: 'Sumitomo Mitsui Financial Group Inc\'s Dividend Analysis',
        date: 'Tue, September 29, 2026 at 11:00 AM UTC 3 min read',
        timestamp: '2026-09-29T11:00:30+00:00',
        preview: 'Sumitomo Mitsui Financial Group Inc. (8316.T) announced an increase in its dividend payout, reflecting strong financial performance and a commitment t...',
        stockSymbol: '8316.T'},
    {id: 'chargepoint-climbs-6-extends-65-monthly-run-evgo-i',
        emoji: '📰',
        title: 'ChargePoint Climbs 6%, Extends 65% Monthly Run; EVgo Inches Higher, Blink Charging Slips',
        date: 'Tue, September 29, 2026 at 4:52 PM UTC 2 min read',
        timestamp: '2026-09-29T16:52:42+00:00',
        preview: 'EVgo\'s stock saw a modest increase as ChargePoint experienced a significant 6% rise, extending its impressive 65% monthly gain. This uptick in EVgo\'s ...',
        stockSymbol: 'EVGO'},
    {id: 'boise-cascade-bcc-on-its-mill-upgrade-story-and-wh',
        emoji: '📰',
        title: 'Boise Cascade (BCC) On Its Mill Upgrade Story And Whether The Stock Looks Fully Valued',
        date: 'Mon, September 28, 2026 at 10:10 PM UTC 4 min read',
        timestamp: '2026-09-28T22:10:43+00:00',
        preview: 'Boise Cascade (BCC) recently discussed its ongoing mill upgrade initiatives, which are aimed at enhancing production efficiency and product quality. T...',
        stockSymbol: 'BCC'},
    {id: 'paychex-just-fell-14-how-does-its-dividend-stack-u',
        emoji: '📰',
        title: 'Paychex Just Fell 14%. How Does Its Dividend Stack Up Against ADP?',
        date: 'Tue, September 29, 2026 at 2:37 PM UTC 3 min read',
        timestamp: '2026-09-29T14:37:31+00:00',
        preview: 'Paychex shares dropped 14% following concerns over its growth prospects and competitive positioning against ADP. This decline raises questions for inv...',
        stockSymbol: 'PAYX'},
    {id: 'consolidated-water-cwco-falls-more-steeply-than-br',
        emoji: '📰',
        title: 'Consolidated Water (CWCO) Falls More Steeply Than Broader Market: What Investors Need to Know',
        date: 'Mon, September 28, 2026 at 9:00 PM UTC 4 min read',
        timestamp: '2026-09-28T21:00:03+00:00',
        preview: 'Consolidated Water (CWCO) experienced a significant decline, falling more steeply than the broader market indices. This downturn raises concerns for i...',
        stockSymbol: 'CWCO'},
    {id: 'at-t-ceo-says-elon-musk-s-spacex-phone-strategy-no',
        emoji: '📰',
        title: 'AT&T CEO says Elon Musk\'s SpaceX phone strategy not "viable"',
        date: 'Tue, September 29, 2026 at 7:16 PM UTC 2 min read',
        timestamp: '2026-09-29T19:16:32+00:00',
        preview: 'AT&T CEO John Stankey criticized Elon Musk\'s SpaceX phone strategy, calling it "not viable." This statement highlights potential challenges for SpaceX...',
        stockSymbol: 'T'},
    {id: 'vici-expands-tenant-base-with-new-century-mile-cen',
        emoji: '📰',
        title: 'VICI Expands Tenant Base With New Century Mile & Century Downs Lease',
        date: 'Tue, September 29, 2026 at 3:46 PM UTC 4 min read',
        timestamp: '2026-09-29T15:46:00+00:00',
        preview: 'VICI Properties has expanded its tenant base by securing a new lease with Century Mile and Century Downs, enhancing its portfolio in the gaming and en...',
        stockSymbol: 'VICI'},
    {id: 'optics-stocks-slide-despite-citi-s-11b-switching-f',
        emoji: '📰',
        title: 'Optics Stocks Slide Despite Citi’s $11B Switching Forecast: Coherent and Applied Optoelectronics Drop 5%, Corning Falls 3%',
        date: 'Mon, September 28, 2026 at 5:52 PM UTC 4 min read',
        timestamp: '2026-09-28T17:52:30+00:00',
        preview: 'Coherent (COHR) shares fell 5% as part of a broader decline in optics stocks, despite Citi\'s optimistic $11 billion forecast for the switching market....',
        stockSymbol: 'COHR'},
    {id: 'hyster-yale-hy-ascends-while-market-falls-some-fac',
        emoji: '📰',
        title: 'Hyster-Yale (HY) Ascends While Market Falls: Some Facts to Note',
        date: 'Mon, September 28, 2026 at 9:00 PM UTC 3 min read',
        timestamp: '2026-09-28T21:00:04+00:00',
        preview: 'Hyster-Yale (HY) saw its stock price rise despite a broader market decline, indicating strong investor confidence in the company\'s performance. This d...',
        stockSymbol: 'HY'},
    {id: 'why-archer-daniels-midland-adm-dipped-more-than-br',
        emoji: '📰',
        title: 'Why Archer Daniels Midland (ADM) Dipped More Than Broader Market Today',
        date: 'Tue, September 29, 2026 at 9:00 PM UTC 2 min read',
        timestamp: '2026-09-29T21:00:02+00:00',
        preview: 'Archer Daniels Midland (ADM) experienced a decline that outpaced the broader market today, primarily due to concerns over rising input costs and poten...',
        stockSymbol: 'ADM'},
    {id: 'should-investors-buy-byd-s-stock-in-october',
        emoji: '📰',
        title: 'Should Investors Buy BYD\'s Stock in October?',
        date: 'Tue, September 29, 2026 at 7:27 PM UTC 3 min read',
        timestamp: '2026-09-29T19:27:00+00:00',
        preview: 'In October, analysts are evaluating whether investors should consider buying BYD\'s stock, following recent fluctuations in the electric vehicle market...',
        stockSymbol: '1211.HK'},
    {id: 'brixmor-property-slate-acquisition-seen-as-rock-so',
        emoji: '📰',
        title: 'Brixmor Property Slate Acquisition Seen as \'Rock Solid\' Investment, UBS Says',
        date: 'Tue, September 29, 2026 at 5:03 PM UTC 4 min read',
        timestamp: '2026-09-29T17:03:36+00:00',
        preview: 'UBS has labeled Brixmor Property Group\'s recent slate acquisition as a "rock solid" investment, highlighting its potential to enhance the company\'s po...',
        stockSymbol: 'BRX'},
    {id: 'saic-wins-u-s-customs-and-border-protection-s-742',
        emoji: '📰',
        title: 'SAIC Wins U.S. Customs and Border Protection’s $742 Million Recompete Contract for Traveler and Cargo Security Systems',
        date: 'Tue, September 29, 2026 at 12:30 PM UTC 3 min read',
        timestamp: '2026-09-29T12:30:00+00:00',
        preview: 'SAIC has secured a $742 million recompete contract with U.S. Customs and Border Protection to enhance traveler and cargo security systems. This win un...',
        stockSymbol: 'SAIC'},
    {id: 'cintas-ctas-beats-estimates-and-raises-fiscal-2027',
        emoji: '📰',
        title: 'Cintas (CTAS) Beats Estimates and Raises Fiscal 2027 Guidance Despite UniFirst Deal Uncertainty',
        date: 'Mon, September 28, 2026 at 10:38 PM UTC 4 min read',
        timestamp: '2026-09-28T22:38:33+00:00',
        preview: 'Cintas (CTAS) reported better-than-expected earnings, surpassing analyst estimates, and raised its fiscal 2027 guidance, indicating strong operational...',
        stockSymbol: 'CTAS'},
    {id: 'how-strong-phase-3-mrd-data-for-zenbexus-in-myelom',
        emoji: '📰',
        title: 'How Strong Phase 3 MRD Data for ZENBEXUS in Myeloma Could Impact Bristol Myers Squibb (BMY) Investors',
        date: 'Wed, September 30, 2026 at 1:08 AM UTC 4 min read',
        timestamp: '2026-09-30T01:08:17+00:00',
        preview: 'Bristol Myers Squibb (BMY) recently reported strong Phase 3 data for its myeloma treatment, ZENBEXUS, which demonstrated significant efficacy in patie...',
        stockSymbol: 'BMY'},
    {id: 'csl-seqirus-expands-u-s-availability-of-influenza',
        emoji: '📰',
        title: 'CSL Seqirus Expands U.S. Availability of Influenza Vaccine following Successful Completion of the 2026/27 Manufacturing Campaign',
        date: 'Tue, September 29, 2026 at 1:30 PM UTC 3 min read',
        timestamp: '2026-09-29T13:30:00+00:00',
        preview: 'CSL Seqirus has successfully completed its 2026/27 influenza vaccine manufacturing campaign, leading to an expansion of its availability in the U.S. m...',
        stockSymbol: 'CSL.AX'},
    {id: 'scalare-partners-tank-stream-labs-expands-into-que',
        emoji: '📰',
        title: 'Scalare Partners\' Tank Stream Labs Expands into Queensland with Brisbane Launch',
        date: 'Mon, September 28, 2026 at 11:00 PM UTC 3 min read',
        timestamp: '2026-09-28T23:00:00+00:00',
        preview: 'Scalare Partners\' Tank Stream Labs has announced its expansion into Queensland with the launch of a new facility in Brisbane. This move is significant...',
        stockSymbol: 'SCP.AX'},
    {id: 'why-phillips-66-psx-is-a-great-dividend-stock-righ',
        emoji: '📰',
        title: 'Why Phillips 66 (PSX) is a Great Dividend Stock Right Now',
        date: 'Tue, September 29, 2026 at 2:45 PM UTC 4 min read',
        timestamp: '2026-09-29T14:45:02+00:00',
        preview: 'Phillips 66 (PSX) has been highlighted as an attractive dividend stock due to its robust financial performance and consistent dividend payments. The c...',
        stockSymbol: 'PSX'},
    {id: 'why-gold-com-gold-dipped-more-than-broader-market',
        emoji: '📰',
        title: 'Why Gold.com (GOLD) Dipped More Than Broader Market Today',
        date: 'Mon, September 28, 2026 at 8:50 PM UTC 2 min read',
        timestamp: '2026-09-28T20:50:04+00:00',
        preview: 'Gold.com (GOLD) experienced a decline today, falling more than the broader market. This dip is attributed to a combination of rising interest rates an...',
        stockSymbol: 'GOLD'},
    {id: 'david-stinnett-purchases-27-000-karman-holdings-sh',
        emoji: '📰',
        title: 'David Stinnett Purchases 27,000 Karman Holdings Shares for $1 Million. Is the Defense Contractor Now a Buy?',
        date: 'Tue, September 29, 2026 at 10:07 PM UTC 2 min read',
        timestamp: '2026-09-29T22:07:01+00:00',
        preview: 'David Stinnett has acquired 27,000 shares of Karman Holdings for $1 million, signaling strong confidence in the defense contractor\'s future prospects....',
        stockSymbol: 'KRMN'},
    {id: 'a-look-back-at-consumer-discretionary-travel-and-v',
        emoji: '📰',
        title: 'A Look Back at Consumer Discretionary - Travel and Vacation Providers Stocks’ Q2 Earnings: Marriott Vacations (NYSE:VAC) Vs The Rest Of The Pack',
        date: 'Tue, September 29, 2026 at 8:08 PM UTC 3 min read',
        timestamp: '2026-09-29T20:08:02+00:00',
        preview: 'Marriott Vacations (NYSE: VAC) reported its Q2 earnings, showcasing resilience in the travel and vacation sector amid broader consumer discretionary t...',
        stockSymbol: 'VAC'},
    {id: 'electronic-components-manufacturing-q2-earnings-am',
        emoji: '📰',
        title: 'Electronic Components & Manufacturing Q2 Earnings: Amphenol (NYSE:APH) is the Best in the Biz',
        date: 'Tue, September 29, 2026 at 7:36 PM UTC 2 min read',
        timestamp: '2026-09-29T19:36:02+00:00',
        preview: 'Amphenol (NYSE: APH) reported strong Q2 earnings, solidifying its position as a leader in the electronic components and manufacturing sector. The comp...',
        stockSymbol: 'APH'},
    {id: 'power-corporation-of-canada-s-dividend-analysis',
        emoji: '📰',
        title: 'Power Corporation of Canada\'s Dividend Analysis',
        date: 'Tue, September 29, 2026 at 11:07 AM UTC 4 min read',
        timestamp: '2026-09-29T11:07:49+00:00',
        preview: 'Power Corporation of Canada (POW.TO) recently announced an increase in its quarterly dividend, reflecting the company\'s strong financial performance a...',
        stockSymbol: 'POW.TO'},
    {id: 'ge-vernova-gev-gains-as-market-dips-what-you-shoul',
        emoji: '📰',
        title: 'GE Vernova (GEV) Gains As Market Dips: What You Should Know',
        date: 'Tue, September 29, 2026 at 9:00 PM UTC 2 min read',
        timestamp: '2026-09-29T21:00:03+00:00',
        preview: 'GE Vernova (GEV) saw an increase in its stock price despite a broader market downturn, highlighting its resilience amid challenging conditions. This p...',
        stockSymbol: 'GE'},
    {id: 'ligand-pharmaceuticals-lgnd-stock-may-be-27-underv',
        emoji: '📰',
        title: 'Ligand Pharmaceuticals (LGND) Stock May Be 27% Undervalued After A New Royalty Deal',
        date: 'Tue, September 29, 2026 at 10:05 AM UTC 2 min read',
        timestamp: '2026-09-29T10:05:03+00:00',
        preview: 'Ligand Pharmaceuticals (LGND) has entered a new royalty deal that analysts believe may indicate the stock is currently undervalued by approximately 27...',
        stockSymbol: 'LGND'},
    {id: 'pitch-based-carbon-fiber-global-strategic-business',
        emoji: '📰',
        title: 'Pitch-based Carbon Fiber - Global Strategic Business Report: Secure Your Share of a $1.2B Market by 2030 as Tariffs Disrupt Supply Chains and Mitsubishi Chemical, Kureha, SGL Carbon, Toray Industries and Resonac Intensify Competition',
        date: 'Mon, September 28, 2026 at 3:36 PM UTC 3 min read',
        timestamp: '2026-09-28T15:36:00+00:00',
        preview: 'The global market for pitch-based carbon fiber is projected to reach $1.2 billion by 2030, driven by increasing competition among major players like M...',
        stockSymbol: '3402.T'},
    {id: 'ares-management-corporation-schedules-earnings-rel',
        emoji: '📰',
        title: 'Ares Management Corporation Schedules Earnings Release and Conference Call for the Third Quarter Ending September 30, 2026',
        date: 'Tue, September 29, 2026 at 10:00 PM UTC 4 min read',
        timestamp: '2026-09-29T22:00:00+00:00',
        preview: 'Ares Management Corporation has announced the scheduling of its earnings release and conference call for the third quarter ending September 30, 2026. ...',
        stockSymbol: 'ARES'},
    {id: 'illinois-tool-works-itw-upgraded-to-buy-here-s-why',
        emoji: '📰',
        title: 'Illinois Tool Works (ITW) Upgraded to Buy: Here\'s Why',
        date: 'Tue, September 29, 2026 at 3:00 PM UTC 4 min read',
        timestamp: '2026-09-29T15:00:04+00:00',
        preview: 'Illinois Tool Works (ITW) has been upgraded to a "Buy" rating by analysts, reflecting increased confidence in the company\'s growth potential and finan...',
        stockSymbol: 'ITW'},
    {id: 'one-gas-ogs-is-a-top-dividend-stock-right-now-shou',
        emoji: '📰',
        title: 'ONE Gas (OGS) is a Top Dividend Stock Right Now: Should You Buy?',
        date: 'Mon, September 28, 2026 at 2:45 PM UTC 3 min read',
        timestamp: '2026-09-28T14:45:03+00:00',
        preview: 'ONE Gas (OGS) has been highlighted as a top dividend stock, attracting attention from investors seeking reliable income sources. The company\'s strong ...',
        stockSymbol: 'OGS'},
    {id: 'glacier-bancorp-inc-announces-third-quarter-earnin',
        emoji: '📰',
        title: 'Glacier Bancorp, Inc. Announces Third Quarter Earnings Release and Conference Call',
        date: 'Mon, September 28, 2026 at 8:30 PM UTC 2 min read',
        timestamp: '2026-09-28T20:30:00+00:00',
        preview: 'Glacier Bancorp, Inc. has announced the release of its third-quarter earnings, scheduled for October 25, 2023, followed by a conference call to discus...',
        stockSymbol: 'GBCI'},
    {id: 'constellation-brands-q2-2027-earnings-what-to-expe',
        emoji: '📰',
        title: 'Constellation Brands’ Q2 2027 Earnings: What to Expect',
        date: 'Tue, September 29, 2026 at 12:33 PM UTC 3 min read',
        timestamp: '2026-09-29T12:33:15+00:00',
        preview: 'Constellation Brands is set to release its Q2 2027 earnings report, with analysts anticipating strong performance driven by robust demand for its beer...',
        stockSymbol: 'STZ'},
    {id: 'palo-alto-networks-stock-rose-nearly-5-as-nvidia-l',
        emoji: '📰',
        title: 'Palo Alto Networks Stock Rose Nearly 5% as Nvidia Launched an AI Agent Safety Platform. Here’s What Palo Alto Is Building on Top of It',
        date: 'Tue, September 29, 2026 at 2:28 PM UTC 3 min read',
        timestamp: '2026-09-29T14:28:49+00:00',
        preview: 'Palo Alto Networks (PANW) shares surged nearly 5% following Nvidia\'s launch of an AI Agent Safety Platform, which enhances cybersecurity measures. Thi...',
        stockSymbol: 'PANW'},
    {id: 'gsk-retains-buy-rating-at-jefferies-as-b7h3-cancer',
        emoji: '📰',
        title: 'GSK retains ‘buy’ rating at Jefferies as B7H3 cancer programme seen as underappreciated',
        date: 'Tue, September 29, 2026 at 11:30 AM UTC 3 min read',
        timestamp: '2026-09-29T11:30:00+00:00',
        preview: 'Jefferies has maintained a \'buy\' rating for GSK, highlighting the potential of its B7H3 cancer program, which they believe is currently undervalued by...',
        stockSymbol: 'GSK.L'},
    {id: 'can-eaton-s-strategic-acquisitions-boost-further-l',
        emoji: '📰',
        title: 'Can Eaton\'s Strategic Acquisitions Boost Further Long-Term Growth?',
        date: 'Mon, September 28, 2026 at 4:07 PM UTC 4 min read',
        timestamp: '2026-09-28T16:07:00+00:00',
        preview: 'Eaton Corporation has made several strategic acquisitions aimed at enhancing its growth trajectory in the long term. These moves are significant for i...',
        stockSymbol: 'ETN'},
    {id: 'rum-stock-ticks-higher-overnight-analyst-sees-94-u',
        emoji: '📰',
        title: 'RUM Stock Ticks Higher Overnight: Analyst Sees 94% Upside As $13B Anthropic Deal Sets Off AI Pivot',
        date: 'Wed, September 30, 2026 at 1:37 AM UTC 2 min read',
        timestamp: '2026-09-30T01:37:50+00:00',
        preview: 'RUM stock experienced a slight increase overnight following an analyst\'s report projecting a 94% upside, fueled by the company\'s $13 billion deal with...',
        stockSymbol: 'RUM'},
    {id: 'why-pagseguro-digital-ltd-pags-dipped-more-than-br',
        emoji: '📰',
        title: 'Why PagSeguro Digital Ltd. (PAGS) Dipped More Than Broader Market Today',
        date: 'Mon, September 28, 2026 at 9:15 PM UTC 3 min read',
        timestamp: '2026-09-28T21:15:04+00:00',
        preview: 'PagSeguro Digital Ltd. (PAGS) experienced a decline today, falling more than the broader market. This drop is attributed to concerns over regulatory c...',
        stockSymbol: 'PAGS'},
    {id: 'anti-drone-counter-uas-market-report-forecasts-gro',
        emoji: '📰',
        title: 'Anti-Drone (Counter-UAS) Market Report Forecasts Growth from $4.8 Billion (2026) to $12.6 Billion by 2036, Profiling Lockheed Martin, Thales, DroneShield & 12 Other Key Players',
        date: 'Tue, September 29, 2026 at 9:30 AM UTC 3 min read',
        timestamp: '2026-09-29T09:30:00+00:00',
        preview: 'The anti-drone market is projected to grow from $4.8 billion in 2026 to $12.6 billion by 2036, with Lockheed Martin (LMT) identified as a key player a...',
        stockSymbol: 'LMT'},
    {id: 'spotify-spot-declines-more-than-market-some-inform',
        emoji: '📰',
        title: 'Spotify (SPOT) Declines More Than Market: Some Information for Investors',
        date: 'Mon, September 28, 2026 at 8:50 PM UTC 2 min read',
        timestamp: '2026-09-28T20:50:04+00:00',
        preview: 'Spotify (SPOT) has experienced a decline that outpaces the broader market, raising concerns among investors about its growth trajectory. This downturn...',
        stockSymbol: 'SPOT'},
    {id: 'magnite-surges-6-as-a-53-ytd-gain-separates-it-fro',
        emoji: '📰',
        title: 'Magnite Surges 6% as a 53% YTD Gain Separates It From Ad-Tech Peers; Trade Desk and AppLovin Tread Water',
        date: 'Tue, September 29, 2026 at 3:22 PM UTC 2 min read',
        timestamp: '2026-09-29T15:22:01+00:00',
        preview: 'Magnite (MGNI) experienced a 6% surge, contributing to a notable 53% year-to-date gain, distinguishing itself from its ad-tech peers like Trade Desk a...',
        stockSymbol: 'MGNI'},
    {id: 'q2-earnings-roundup-lovesac-nasdaq-love-and-the-re',
        emoji: '📰',
        title: 'Q2 Earnings Roundup: Lovesac (NASDAQ:LOVE) And The Rest Of The Consumer Discretionary - Home Furnishings Segment',
        date: 'Tue, September 29, 2026 at 7:28 PM UTC 3 min read',
        timestamp: '2026-09-29T19:28:02+00:00',
        preview: 'Lovesac (NASDAQ: LOVE) reported its Q2 earnings, showcasing strong performance within the consumer discretionary home furnishings segment. The results...',
        stockSymbol: 'LOVE'},
    {id: 'urbn-vs-zgn-which-stock-should-value-investors-buy',
        emoji: '📰',
        title: 'URBN vs. ZGN: Which Stock Should Value Investors Buy Now?',
        date: 'Tue, September 29, 2026 at 2:40 PM UTC 3 min read',
        timestamp: '2026-09-29T14:40:04+00:00',
        preview: 'In a recent analysis comparing URBN and ZGN, investors are encouraged to consider ZGN for its strong fundamentals and growth potential. The evaluation...',
        stockSymbol: 'ZGN'},
    {id: 'asml-stock-surges-3-8-as-ai-rebound-returns-to-lit',
        emoji: '📰',
        title: 'ASML Stock Surges 3.8% as AI Rebound Returns to Lithography',
        date: 'Tue, September 29, 2026 at 6:48 PM UTC 2 min read',
        timestamp: '2026-09-29T18:48:36+00:00',
        preview: 'ASML\'s stock rose 3.8% following a rebound in demand for artificial intelligence (AI) technologies, which is positively impacting the lithography equi...',
        stockSymbol: 'ASML'},
    {id: 'exxon-mobil-holdings-xom-gains-as-market-dips-what',
        emoji: '📰',
        title: 'Exxon Mobil Holdings (XOM) Gains As Market Dips: What You Should Know',
        date: 'Mon, September 28, 2026 at 8:45 PM UTC 2 min read',
        timestamp: '2026-09-28T20:45:04+00:00',
        preview: 'Exxon Mobil Holdings (XOM) saw gains despite a broader market dip, reflecting its resilience amid economic uncertainties. This performance is signific...',
        stockSymbol: 'XOM'},
    {id: 'earnings-to-watch-conagra-cag-reports-q3-results-t',
        emoji: '📰',
        title: 'Earnings To Watch: Conagra (CAG) Reports Q3 Results Tomorrow',
        date: 'Tue, September 29, 2026 at 3:00 AM UTC 2 min read',
        timestamp: '2026-09-29T03:00:52+00:00',
        preview: 'Conagra Brands (CAG) is set to report its Q3 earnings results tomorrow, which will provide key insights into the company\'s financial performance amid ...',
        stockSymbol: 'CAG'},
    {id: 'wall-street-bulls-look-optimistic-about-nutanix-nt',
        emoji: '📰',
        title: 'Wall Street Bulls Look Optimistic About Nutanix (NTNX): Should You Buy?',
        date: 'Tue, September 29, 2026 at 12:30 PM UTC 4 min read',
        timestamp: '2026-09-29T12:30:04+00:00',
        preview: 'Nutanix (NTNX) has garnered positive attention from Wall Street analysts, who express optimism about the company\'s growth potential and market positio...',
        stockSymbol: 'NTNX'},
    {id: 'amkor-technology-amkr-advances-while-market-declin',
        emoji: '📰',
        title: 'Amkor Technology (AMKR) Advances While Market Declines: Some Information for Investors',
        date: 'Tue, September 29, 2026 at 8:50 PM UTC 4 min read',
        timestamp: '2026-09-29T20:50:02+00:00',
        preview: 'Amkor Technology (AMKR) has shown resilience by advancing in stock price despite a broader market decline. This performance highlights the company\'s s...',
        stockSymbol: 'AMKR'},
    {id: 'mitsui-co-ltd-s-dividend-analysis',
        emoji: '📰',
        title: 'Mitsui & Co Ltd\'s Dividend Analysis',
        date: 'Tue, September 29, 2026 at 11:03 AM UTC 3 min read',
        timestamp: '2026-09-29T11:03:12+00:00',
        preview: 'Mitsui & Co Ltd (8031.T) announced an increase in its dividend payout, reflecting strong financial performance and a commitment to returning value to ...',
        stockSymbol: '8031.T'},
    {id: 'shadow-bank-boss-accused-of-1-3bn-fraud-blames-bar',
        emoji: '📰',
        title: 'Shadow bank boss accused of £1.3bn fraud blames Barclays for collapse',
        date: 'Mon, September 28, 2026 at 2:41 PM UTC 3 min read',
        timestamp: '2026-09-28T14:41:30+00:00',
        preview: 'The CEO of a shadow banking firm has been accused of committing £1.3 billion in fraud, claiming that Barclays\' actions contributed to the firm\'s colla...',
        stockSymbol: 'BARC.L'},
    {id: 'bank-of-america-earnings-preview-what-to-expect',
        emoji: '📰',
        title: 'Bank of America Earnings Preview: What to Expect',
        date: 'Tue, September 29, 2026 at 2:19 PM UTC 4 min read',
        timestamp: '2026-09-29T14:19:38+00:00',
        preview: 'Bank of America is set to release its earnings report, with analysts anticipating a mixed performance due to ongoing economic challenges and interest ...',
        stockSymbol: 'BAC'},
    {id: 'why-associated-banc-corp-asb-is-a-great-dividend-s',
        emoji: '📰',
        title: 'Why Associated Banc-Corp (ASB) is a Great Dividend Stock Right Now',
        date: 'Mon, September 28, 2026 at 2:45 PM UTC 3 min read',
        timestamp: '2026-09-28T14:45:04+00:00',
        preview: 'Associated Banc-Corp (ASB) has been highlighted as an attractive dividend stock due to its consistent dividend payments and a strong financial positio...',
        stockSymbol: 'ASB'},
    {id: 'amd-expands-ai-expertise-with-world-labs-acquisiti',
        emoji: '📰',
        title: 'AMD Expands AI Expertise With World Labs Acquisition',
        date: 'Tue, September 29, 2026 at 8:08 PM UTC 4 min read',
        timestamp: '2026-09-29T20:08:34+00:00',
        preview: 'AMD has acquired World Labs, a move aimed at enhancing its artificial intelligence capabilities. This acquisition is significant for investors as it p...',
        stockSymbol: 'AMD'},
    {id: 'ntap-stock-hits-record-high-netapp-expands-strateg',
        emoji: '📰',
        title: 'NTAP Stock Hits Record High: NetApp Expands Strategic Partnerships With SAP, Oracle, and Supermicro To Drive Cloud Infrastructure',
        date: 'Tue, September 29, 2026 at 7:47 PM UTC 4 min read',
        timestamp: '2026-09-29T19:47:48+00:00',
        preview: 'NTAP stock reached a record high following NetApp\'s announcement of expanded strategic partnerships with SAP, Oracle, and Supermicro aimed at enhancin...',
        stockSymbol: 'NTAP'},
    {id: 'snowflake-slides-4-on-proposed-3-5b-convertible-of',
        emoji: '📰',
        title: 'Snowflake Slides 4% on Proposed $3.5B Convertible Offering; Oracle Falls 3%, Datadog Drops 4%',
        date: 'Mon, September 28, 2026 at 1:45 PM UTC 2 min read',
        timestamp: '2026-09-28T13:45:51+00:00',
        preview: 'Datadog (DDOG) experienced a 4% decline, alongside Oracle and Snowflake, following the announcement of Snowflake\'s proposed $3.5 billion convertible o...',
        stockSymbol: 'DDOG'},
    {id: 'alexandria-real-estate-equities-inc-announces-clos',
        emoji: '📰',
        title: 'Alexandria Real Estate Equities, Inc. Announces Closing of Amended and Restated $5.0 Billion Unsecured Senior Line of Credit',
        date: 'Mon, September 28, 2026 at 8:10 PM UTC 2 min read',
        timestamp: '2026-09-28T20:10:00+00:00',
        preview: 'Alexandria Real Estate Equities, Inc. has successfully closed an amended and restated $5.0 billion unsecured senior line of credit. This move enhances...',
        stockSymbol: 'ARE'},
    {id: 'arlo-debuts-essential-solar-security-camera-design',
        emoji: '📰',
        title: 'Arlo Debuts Essential Solar Security Camera Designed for Year-Round, Low-Maintenance Protection',
        date: 'Tue, September 29, 2026 at 12:04 PM UTC 2 min read',
        timestamp: '2026-09-29T12:04:00+00:00',
        preview: 'Arlo Technologies has launched its Essential Solar Security Camera, designed for year-round, low-maintenance surveillance. This innovative product enh...',
        stockSymbol: 'ARLO'},
    {id: 'can-redwire-s-digital-engineering-accelerate-space',
        emoji: '📰',
        title: 'Can Redwire\'s Digital Engineering Accelerate Space Mission Design?',
        date: 'Tue, September 29, 2026 at 12:51 PM UTC 3 min read',
        timestamp: '2026-09-29T12:51:00+00:00',
        preview: 'Redwire has announced advancements in its digital engineering capabilities aimed at enhancing space mission design. This development is significant fo...',
        stockSymbol: 'RDW'},
    {id: 'abm-and-arizona-cardinals-highlight-partnership-at',
        emoji: '📰',
        title: 'ABM and Arizona Cardinals Highlight Partnership at State Farm Stadium',
        date: 'Tue, September 29, 2026 at 12:00 PM UTC 2 min read',
        timestamp: '2026-09-29T12:00:00+00:00',
        preview: 'ABM Industries has showcased its partnership with the Arizona Cardinals at State Farm Stadium, emphasizing its role in providing essential services fo...',
        stockSymbol: 'ABM'},
    {id: 'louisiana-pacific-lpx-is-the-market-missing-its-si',
        emoji: '📰',
        title: 'Louisiana-Pacific (LPX): Is the Market Missing Its Siding Transformation?',
        date: 'Mon, September 28, 2026 at 8:35 PM UTC 3 min read',
        timestamp: '2026-09-28T20:35:38+00:00',
        preview: 'Louisiana-Pacific (LPX) is undergoing a significant transformation in its siding business, which could enhance its market position and profitability. ...',
        stockSymbol: 'LPX'},
    {id: 'does-united-parks-resorts-prks-new-leadership-spli',
        emoji: '📰',
        title: 'Does United Parks & Resorts (PRKS) New Leadership Split Reframe Its Core Operational Turnaround Story?',
        date: 'Mon, September 28, 2026 at 10:10 PM UTC 4 min read',
        timestamp: '2026-09-28T22:10:43+00:00',
        preview: 'United Parks & Resorts (PRKS) has recently undergone a leadership change, which may significantly impact its operational turnaround strategy. This shi...',
        stockSymbol: 'PRKS'},
    {id: 'reflecting-on-consumer-discretionary-broadcasting',
        emoji: '📰',
        title: 'Reflecting On Consumer Discretionary - Broadcasting Stocks’ Q2 Earnings: Gray Television (NYSE:GTN)',
        date: 'Tue, September 29, 2026 at 6:32 PM UTC 4 min read',
        timestamp: '2026-09-29T18:32:02+00:00',
        preview: 'Gray Television (NYSE: GTN) reported its Q2 earnings, showcasing a mixed performance amid challenges in the consumer discretionary sector. The results...',
        stockSymbol: 'GTN'},
    {id: 'morgan-stanley-s-new-lab-to-test-wall-street-s-fut',
        emoji: '📰',
        title: 'Morgan Stanley\'s new lab to test Wall Street\'s future',
        date: 'Tue, September 29, 2026 at 9:10 PM UTC 4 min read',
        timestamp: '2026-09-29T21:10:33+00:00',
        preview: 'Morgan Stanley has launched a new lab aimed at exploring innovative technologies and strategies to shape the future of Wall Street. This initiative is...',
        stockSymbol: 'MS'},
    {id: 'larimar-therapeutics-strengthens-executive-leaders',
        emoji: '📰',
        title: 'Larimar Therapeutics Strengthens Executive Leadership with Appointment of John Harlow as President and Chief Operating Officer',
        date: 'Tue, September 29, 2026 at 8:05 PM UTC 3 min read',
        timestamp: '2026-09-29T20:05:00+00:00',
        preview: 'Larimar Therapeutics has appointed John Harlow as President and Chief Operating Officer, enhancing its executive leadership team. This strategic move ...',
        stockSymbol: 'LRMR'},
    {id: 'should-value-investors-buy-sensata-technologies-ho',
        emoji: '📰',
        title: 'Should Value Investors Buy Sensata Technologies Holding (ST) Stock?',
        date: 'Tue, September 29, 2026 at 12:40 PM UTC 4 min read',
        timestamp: '2026-09-29T12:40:04+00:00',
        preview: 'Sensata Technologies Holding (ST) is currently being evaluated by value investors as its stock shows potential for growth amid favorable market condit...',
        stockSymbol: 'ST'},
    {id: 'toll-brothers-tol-opens-oakbend-amenity-center-on',
        emoji: '📰',
        title: 'Toll Brothers (TOL) Opens Oakbend Amenity Center On A Valuation That Still Looks Cheap',
        date: 'Mon, September 28, 2026 at 4:07 PM UTC 2 min read',
        timestamp: '2026-09-28T16:07:38+00:00',
        preview: 'Toll Brothers (TOL) has officially opened the Oakbend Amenity Center, enhancing its community offerings and potentially increasing property values in ...',
        stockSymbol: 'TOL'},
    {id: 'american-vanguard-announces-acquisition-of-u-s-cro',
        emoji: '📰',
        title: 'American Vanguard Announces Acquisition of U.S. Crop-Protection Products from Syngenta',
        date: 'Tue, September 29, 2026 at 1:00 PM UTC 4 min read',
        timestamp: '2026-09-29T13:00:00+00:00',
        preview: 'American Vanguard Corporation has announced the acquisition of U.S. crop-protection products from Syngenta, a strategic move aimed at expanding its pr...',
        stockSymbol: 'AVD'},
    {id: 'can-core-growth-help-cpay-sustain-its-strong-reven',
        emoji: '📰',
        title: 'Can Core Growth Help CPAY Sustain Its Strong Revenue Momentum?',
        date: 'Mon, September 28, 2026 at 4:26 PM UTC 2 min read',
        timestamp: '2026-09-28T16:26:00+00:00',
        preview: 'CPAY is exploring its core growth strategies to maintain its robust revenue momentum, which has been a key driver of its recent performance. This focu...',
        stockSymbol: 'CPAY'},
    {id: 'ingram-micro-ingm-buy-sell-or-hold-post-q2-earning',
        emoji: '📰',
        title: 'Ingram Micro (INGM): Buy, Sell, or Hold Post Q2 Earnings?',
        date: 'Mon, September 28, 2026 at 4:38 PM UTC 4 min read',
        timestamp: '2026-09-28T16:38:36+00:00',
        preview: 'Ingram Micro (INGM) recently reported its Q2 earnings, which showed mixed results, prompting analysts to reassess their ratings. The company\'s revenue...',
        stockSymbol: 'INGM'},
    {id: 'ntt-inc-s-dividend-analysis',
        emoji: '📰',
        title: 'NTT Inc\'s Dividend Analysis',
        date: 'Tue, September 29, 2026 at 11:03 AM UTC 2 min read',
        timestamp: '2026-09-29T11:03:36+00:00',
        preview: 'NTT Inc (9432.T) has announced a dividend increase, reflecting its strong financial performance and commitment to returning value to shareholders. Thi...',
        stockSymbol: '9432.T'},
    {id: 'down-15-5-in-4-weeks-here-s-why-you-should-you-buy',
        emoji: '📰',
        title: 'Down 15.5% in 4 Weeks, Here\'s Why You Should You Buy the Dip in BILL Holdings (BILL)',
        date: 'Tue, September 29, 2026 at 12:35 PM UTC 3 min read',
        timestamp: '2026-09-29T12:35:01+00:00',
        preview: 'BILL Holdings\' stock has declined 15.5% over the past four weeks, prompting analysts to suggest that now may be an opportune time to buy the dip. The ...',
        stockSymbol: 'BILL'},
    {id: 'constellation-energy-corporation-ceg-sees-a-more-s',
        emoji: '📰',
        title: 'Constellation Energy Corporation (CEG) Sees a More Significant Dip Than Broader Market: Some Facts to Know',
        date: 'Mon, September 28, 2026 at 8:45 PM UTC 3 min read',
        timestamp: '2026-09-28T20:45:03+00:00',
        preview: 'Constellation Energy Corporation (CEG) experienced a notable decline, surpassing the broader market\'s downturn. This dip raises concerns for investors...',
        stockSymbol: 'CEG'},
    {id: 'pepsico-just-got-a-19-price-target-cut-ahead-of-ea',
        emoji: '📰',
        title: 'PepsiCo Just Got a 19% Price-Target Cut Ahead of Earnings',
        date: 'Tue, September 29, 2026 at 7:08 PM UTC 4 min read',
        timestamp: '2026-09-29T19:08:41+00:00',
        preview: 'PepsiCo recently faced a 19% reduction in its price target ahead of its upcoming earnings report, reflecting concerns over potential revenue growth an...',
        stockSymbol: 'PEP'},
    {id: 'nutrien-ltd-s-dividend-analysis',
        emoji: '📰',
        title: 'Nutrien Ltd\'s Dividend Analysis',
        date: 'Tue, September 29, 2026 at 11:09 AM UTC 4 min read',
        timestamp: '2026-09-29T11:09:46+00:00',
        preview: 'Nutrien Ltd (NTR.TO) recently announced an increase in its quarterly dividend, reflecting the company\'s strong financial performance and commitment to...',
        stockSymbol: 'NTR.TO'},
    {id: 'as-crisis-events-intensify-blackberry-and-the-amer',
        emoji: '📰',
        title: 'As Crisis Events Intensify, BlackBerry and the American Red Cross Renew Commitment to Secure and Trusted Emergency Communications',
        date: 'Tue, September 29, 2026 at 1:00 PM UTC 3 min read',
        timestamp: '2026-09-29T13:00:00+00:00',
        preview: 'BlackBerry Limited (BB.TO) has renewed its partnership with the American Red Cross to enhance secure and trusted emergency communications amidst escal...',
        stockSymbol: 'BB.TO'},
    {id: 'albertsons-companies-announces-second-quarter-fisc',
        emoji: '📰',
        title: 'Albertsons Companies Announces Second Quarter Fiscal 2026 Earnings Release and Conference Call Date',
        date: 'Tue, September 29, 2026 at 8:05 PM UTC 3 min read',
        timestamp: '2026-09-29T20:05:53+00:00',
        preview: 'Albertsons Companies has announced the release date for its second quarter fiscal 2026 earnings report, scheduled for June 15, 2026. The company will ...',
        stockSymbol: '',
        link: ''},
    {id: 'federal-reserve-staffer-removed-sensitive-files-be',
        emoji: '📊',
        title: 'Federal Reserve Staffer Removed Sensitive Files Before Retiring, Report Finds',
        date: 'Mon, September 28, 2026 at 4:54 PM UTC 3 min read',
        timestamp: '2026-09-28T16:54:00+00:00',
        preview: 'A recent report from the Wall Street Journal reveals that a Federal Reserve staffer removed sensitive files prior to their retirement, raising concern...',
        stockSymbol: '',
        link: ''},
    {id: 'monetary-policy-overtakes-inflation-as-cfos-top-co',
        emoji: '📊',
        title: 'Monetary policy overtakes inflation as CFOs top concern',
        date: 'Mon, September 28, 2026 at 5:51 PM UTC 3 min read',
        timestamp: '2026-09-28T17:51:04+00:00',
        preview: 'In a recent survey, Chief Financial Officers (CFOs) have identified monetary policy as their primary concern, surpassing inflation for the first time ...',
        stockSymbol: '',
        link: ''},
    {id: 'key-us-data-this-week-seen-bolstering-case-for-oct',
        emoji: '📊',
        title: 'Key US Data This Week Seen Bolstering Case for October Rate Hike - Bloomberg.com',
        date: 'Mon, September 28, 2026 at 10:00 AM UTC 3 min read',
        timestamp: '2026-09-28T10:00:00+00:00',
        preview: 'This week, key U.S. economic data is anticipated to strengthen the argument for an interest rate hike by the Federal Reserve in October. Analysts are ...',
        stockSymbol: '',
        link: ''},
    {id: 'we-re-witnessing-the-stock-market-do-something-for',
        emoji: '📰',
        title: 'We\'re Witnessing the Stock Market Do Something for Only the 3rd Time in 156 Years, and History Is Crystal Clear About What\'s Next for Stocks',
        date: 'Sun, September 27, 2026 at 10:57 AM UTC 3 min read',
        timestamp: '2026-09-27T10:57:59+00:00',
        preview: 'The stock market is currently experiencing a rare phenomenon, occurring for only the third time in 156 years, which could have significant implication...',
        stockSymbol: '',
        link: ''},
    {id: 'prediction-a-stock-market-crash-is-coming-heres-th',
        emoji: '🔴',
        title: 'Prediction: A Stock Market Crash Is Coming. Heres the One Move You Should Make, According to History.',
        date: 'Sun, September 27, 2026 at 12:05 PM UTC 3 min read',
        timestamp: '2026-09-27T12:05:00+00:00',
        preview: 'A recent article from The Motley Fool warns that a stock market crash may be on the horizon, drawing on historical trends to support this prediction. ...',
        stockSymbol: '',
        link: ''},
    {id: 'silgan-to-release-third-quarter-2026-earnings-resu',
        emoji: '📰',
        title: 'Silgan to Release Third Quarter 2026 Earnings Results on October 29, 2026',
        date: 'Fri, September 25, 2026 at 9:20 PM UTC 3 min read',
        timestamp: '2026-09-25T21:20:00+00:00',
        preview: 'Silgan Holdings Inc. has announced that it will release its third quarter 2026 earnings results on October 29, 2026. Investors will be keenly watching...',
        stockSymbol: '',
        link: ''},
    {id: 'reducing-environmental-hazards-in-k12-schools-can',
        emoji: '📰',
        title: 'Reducing Environmental Hazards In K12 Schools Can Boost Students Lifetime Earnings - urban.org',
        date: 'Fri, September 25, 2026 at 12:00 PM UTC 3 min read',
        timestamp: '2026-09-25T12:00:00+00:00',
        preview: 'A recent study by Urban Institute highlights that reducing environmental hazards in K-12 schools can significantly enhance students\' lifetime earnings...',
        stockSymbol: '',
        link: ''},
    {id: 'micron-technology-stock-wavers-ahead-of-fiscal-q4',
        emoji: '📰',
        title: 'Micron Technology Stock Wavers Ahead Of Fiscal Q4 Earnings Report - Investor\'s Business Daily',
        date: 'Fri, September 25, 2026 at 8:20 PM UTC 3 min read',
        timestamp: '2026-09-25T20:20:00+00:00',
        preview: 'Micron Technology\'s stock has shown volatility as investors await its fiscal Q4 earnings report, scheduled for release on September 28. The semiconduc...',
        stockSymbol: '',
        link: ''},
    {id: 'fed-s-williams-says-it-is-reasonable-to-see-anothe',
        emoji: '📊',
        title: 'Fed\'s Williams says it is reasonable to see another US rate hike this year',
        date: 'Thu, September 24, 2026 at 2:17 PM UTC 3 min read',
        timestamp: '2026-09-24T14:17:57+00:00',
        preview: 'In a recent statement, Federal Reserve Bank of New York President John Williams indicated that it is reasonable to anticipate another interest rate hi...',
        stockSymbol: '',
        link: ''},
    {id: 'rising-treasury-yields-could-push-car-loan-rates-h',
        emoji: '📊',
        title: 'Rising Treasury yields could push car loan rates higher, experts say. What buyers need to know',
        date: 'Thu, September 24, 2026 at 4:14 PM UTC 3 min read',
        timestamp: '2026-09-24T16:14:35+00:00',
        preview: 'Rising Treasury yields are expected to lead to higher car loan rates, according to financial experts. As the yield on the 10-year Treasury note has re...',
        stockSymbol: '',
        link: ''},
    {id: 'commentary-passive-investing-that-s-p-500-index-fu',
        emoji: '📰',
        title: 'COMMENTARY: Passive investing? That S&P 500 index fund is basically a tech fund',
        date: 'Wed, September 23, 2026 at 11:40 PM UTC 3 min read',
        timestamp: '2026-09-23T23:40:35+00:00',
        preview: 'The S&P 500 index, often viewed as a benchmark for passive investing, has increasingly become dominated by technology stocks. As of recent data, tech ...',
        stockSymbol: '',
        link: ''},
    {id: 'dow-jones-futures-fall-after-nasdaq-hits-new-high',
        emoji: '🔴',
        title: 'Dow Jones Futures Fall After Nasdaq Hits New High; Sandisk, Micron Trigger Buy Signals - Investor\'s Business Daily',
        date: 'Wed, September 23, 2026 at 12:05 PM UTC 3 min read',
        timestamp: '2026-09-23T12:05:00+00:00',
        preview: 'Dow Jones futures experienced a decline following the Nasdaq\'s recent surge to a new record high, reflecting a mixed sentiment in the market. Notably,...',
        stockSymbol: '',
        link: ''},
    {id: '5-things-to-know-before-the-stock-market-opens-on',
        emoji: '📰',
        title: '5 Things to Know Before the Stock Market Opens on Wednesday',
        date: 'Wed, September 23, 2026 at 12:18 PM UTC 3 min read',
        timestamp: '2026-09-23T12:18:54+00:00',
        preview: 'As the stock market prepares to open on Wednesday, investors should be aware of several key developments. Notably, major indices are poised for a mixe...',
        stockSymbol: '',
        link: ''},
    {id: 'anthropic-ipo-what-10b5-1-plans-mean-for-employees',
        emoji: '📰',
        title: 'Anthropic IPO: What 10b5-1 Plans Mean For Employees',
        date: 'Tue, September 22, 2026 at 8:28 PM UTC 3 min read',
        timestamp: '2026-09-22T20:28:18+00:00',
        preview: 'Anthropic, an AI research company, is preparing for its initial public offering (IPO) and has implemented 10b5-1 plans to facilitate stock sales for e...',
        stockSymbol: '',
        link: ''},
    {id: 'anthropics-ipo-will-happen-a-month-later-than-expe',
        emoji: '📰',
        title: 'Anthropics IPO Will Happen a Month Later Than Expected',
        date: 'Tue, September 22, 2026 at 6:45 PM UTC 3 min read',
        timestamp: '2026-09-22T18:45:29+00:00',
        preview: 'Anthropic, the artificial intelligence startup, has announced that its initial public offering (IPO) will be delayed by one month, now scheduled for l...',
        stockSymbol: '',
        link: ''},
    {id: 'northpointe-bancshares-inc-announces-date-of-third',
        emoji: '📰',
        title: 'Northpointe Bancshares, Inc. Announces Date of Third Quarter 2026 Earnings Release and Conference Call',
        date: 'Mon, September 21, 2026 at 8:27 PM UTC 3 min read',
        timestamp: '2026-09-21T20:27:00+00:00',
        preview: 'Northpointe Bancshares, Inc. has announced that it will release its earnings for the third quarter of 2026 on November 3, 2026. The company will also ...',
        stockSymbol: '',
        link: ''},
    {id: 'when-will-pharming-group-reveal-its-2024-financial',
        emoji: '🚀',
        title: 'When Will Pharming Group Reveal Its 2024 Financial Performance? Key Date Announced',
        date: 'Mon, September 21, 2026 at 8:54 PM UTC 3 min read',
        timestamp: '2026-09-21T20:54:01+00:00',
        preview: 'Pharming Group has announced that it will disclose its financial performance for the year 2024 on March 12, 2025. This announcement is significant for...',
        stockSymbol: '',
        link: ''}
];

// Render news items into the sidebar
function renderNewsItems() {
    const container = document.getElementById('news-items');
    if (!container) return;
    
    // Sort all items by date (newest first)
    const sortedItems = [...newsItems].sort((a, b) => {
        const dateA = new Date(a.date);
        const dateB = new Date(b.date);
        return dateB - dateA;
    });
    
    // Separate stock news and general news from sorted items
    const stockNews = sortedItems.filter(item => item.stockSymbol);
    const generalNews = sortedItems.filter(item => !item.stockSymbol);
    
    // Show 1 general + 4 stock news
    const displayItems = [];
    if (generalNews.length > 0) displayItems.push(generalNews[0]);
    displayItems.push(...stockNews.slice(0, 4));
    
    container.innerHTML = displayItems.map(item => {
        const url = item.stockSymbol ? `stocks/${item.stockSymbol}.html` : `news.html#${item.id}`;
        return `
        <div class="news-item" style="padding: 8px; margin-bottom: 8px; border-bottom: 1px solid var(--border-color); cursor: pointer;" onclick="window.location.href='${url}'">
            <div style="font-weight: 600; color: var(--text-primary); font-size: 0.85rem; margin-bottom: 3px;">${item.emoji} ${item.title}</div>
            <div style="color: var(--text-secondary); font-size: 0.7rem; margin-bottom: 2px;" data-timestamp="${item.timestamp || ''}" class="article-date">${item.date}</div>
            <div style="color: var(--text-secondary); font-size: 0.75rem; line-height: 1.3;">${item.preview}</div>
        </div>
        `;
    }).join('');
}

if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', renderNewsItems);
} else {
    renderNewsItems();
}
